# Copyright 2026 Enactic, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

base_link:
  origin:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: -0
    yaw: 0
  geometry:
    mesh: "package://openarm_description/assets/robot/openarm_v2.0/meshes/arm/visual/base_link.dae"
    scale:
      x: 1
      y: 1
      z: 1
link1:
  origin:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: -0
    yaw: 0
  geometry:
    mesh: "package://openarm_description/assets/robot/openarm_v2.0/meshes/arm/visual/link1.dae"
    scale:
      x: 1
      y: 1
      z: 1
link2:
  origin:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: -0
    yaw: 0
  geometry:
    mesh: "package://openarm_description/assets/robot/openarm_v2.0/meshes/arm/visual/link2.dae"
    scale:
      x: 1
      y: 1
      z: 1
link3:
  origin:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: -0
    yaw: 0
  geometry:
    mesh: "package://openarm_description/assets/robot/openarm_v2.0/meshes/arm/visual/link3.dae"
    scale:
      x: 1
      y: 1
      z: 1
link4:
  origin:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: -0
    yaw: 0
  geometry:
    mesh: "package://openarm_description/assets/robot/openarm_v2.0/meshes/arm/visual/link4.dae"
    scale:
      x: 1
      y: 1
      z: 1
link5:
  origin:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: -0
    yaw: 0
  geometry:
    mesh: "package://openarm_description/assets/robot/openarm_v2.0/meshes/arm/visual/link5.dae"
    scale:
      x: 1
      y: 1
      z: 1
link6:
  origin:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: -0
    yaw: 0
  geometry:
    mesh: "package://openarm_description/assets/robot/openarm_v2.0/meshes/arm/visual/link6.dae"
    scale:
      x: 1
      y: 1
      z: 1
