# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: OBSERVATIONS
        layers: [512, 256]
        activations: relu
    output: tanh(ACTIONS)
  critic_1:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: concatenate([OBSERVATIONS, ACTIONS])
        layers: [512, 256]
        activations: relu
    output: ONE
  critic_2:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: concatenate([OBSERVATIONS, ACTIONS])
        layers: [512, 256]
        activations: relu
    output: ONE
  target_critic_1:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: concatenate([OBSERVATIONS, ACTIONS])
        layers: [512, 256]
        activations: relu
    output: ONE
  target_critic_2:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: concatenate([OBSERVATIONS, ACTIONS])
        layers: [512, 256]
        activations: relu
    output: ONE


# Replay memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: 16000


# SAC agent configuration (field names are from SAC_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/agents/sac.html
agent:
  class: SAC
  gradient_steps: 1
  batch_size: 4096
  discount_factor: 0.99
  polyak: 0.005
  learning_rate: 5.0e-4
  learning_rate_scheduler: null
  learning_rate_scheduler_kwargs: null
  observation_preprocessor: RunningStandardScaler
  observation_preprocessor_kwargs: null
  state_preprocessor: null
  state_preprocessor_kwargs: null
  random_timesteps: 50
  learning_starts: 50
  grad_norm_clip: 0
  learn_entropy: True
  initial_entropy_value: 0.2
  target_entropy: null
  rewards_shaper: null
  mixed_precision: False
  # logging and checkpoint
  experiment:
    directory: "ant_direct"
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 160000
  environment_info: log
