# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: OBSERVATIONS
        layers: [512, 256]
        activations: relu
    output: tanh(ACTIONS)
  target_policy:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: OBSERVATIONS
        layers: [512, 256]
        activations: relu
    output: tanh(ACTIONS)
  critic_1:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: concatenate([OBSERVATIONS, ACTIONS])
        layers: [512, 256]
        activations: relu
    output: ONE
  critic_2:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: concatenate([OBSERVATIONS, ACTIONS])
        layers: [512, 256]
        activations: relu
    output: ONE
  target_critic_1:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: concatenate([OBSERVATIONS, ACTIONS])
        layers: [512, 256]
        activations: relu
    output: ONE
  target_critic_2:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: concatenate([OBSERVATIONS, ACTIONS])
        layers: [512, 256]
        activations: relu
    output: ONE


# Replay memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: 16000


# TD3 agent configuration (field names are from TD3_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/agents/td3.html
agent:
  class: TD3
  gradient_steps: 1
  batch_size: 4096
  discount_factor: 0.99
  polyak: 0.005
  learning_rate: 5.0e-4
  learning_rate_scheduler: null
  learning_rate_scheduler_kwargs: null
  observation_preprocessor: RunningStandardScaler
  observation_preprocessor_kwargs: null
  state_preprocessor: null
  state_preprocessor_kwargs: null
  random_timesteps: 50
  learning_starts: 50
  grad_norm_clip: 0
  exploration_noise: GaussianNoise
  exploration_noise_kwargs:
    mean: 0.0
    std: 0.1
  exploration_scheduler: max(1 - timestep / timesteps, 0.01)
  policy_delay: 2
  smooth_regularization_noise: GaussianNoise
  smooth_regularization_noise_kwargs:
    mean: 0.0
    std: 0.2
  smooth_regularization_clip: 0.5
  rewards_shaper: null
  mixed_precision: False
  # logging and checkpoint
  experiment:
    directory: "ant_direct"
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 160000
  environment_info: log
