# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Print the OVRTX shader cache collection identifier for the current lockfile.

The OVRTX NV driver PSO cache (nv_shadercache/GLCache) is generated by the
NVIDIA Vulkan driver for a specific ovrtx version. The ovrtx version determines
the shader permutation set; the driver version and GPU architecture are handled
in the enclosing action via nvidia-smi.
"""

import re
import sys

LOCKFILE = "uv.lock"


def read_packages(text: str) -> dict[str, str]:
    """Map each ``[[package]]`` name in the lockfile to the raw text of its block."""
    packages = {}
    for block in re.split(r"^\[\[package\]\]$", text, flags=re.MULTILINE)[1:]:
        block = re.split(r"^\[", block, flags=re.MULTILINE)[0]
        name = re.search(r'^name = "(.*)"$', block, flags=re.MULTILINE)
        if name:
            packages[name.group(1)] = block
    return packages


def main() -> int:
    with open(LOCKFILE, encoding="utf-8") as handle:
        packages = read_packages(handle.read())

    try:
        ovrtx = re.search(r'^version = "(.*)"$', packages["ovrtx"], flags=re.MULTILINE).group(1)
    except (AttributeError, KeyError) as exc:
        print(f"::error::{LOCKFILE} has no version entry for {exc}", file=sys.stderr)
        return 1

    print(f"ovrtx{ovrtx}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
