# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Set up VS Code and Cursor for an Isaac Lab repository or external project.

The script writes editor settings and a machine-local ``pyrightconfig.json``. The Pyright
configuration extends the project's checked-in ``pyproject.toml`` and adds import roots
discovered from the active Python environment. This supports source, editable, wheel, and
Isaac Sim binaries installations without storing machine-specific paths in version control.
"""

import argparse
import pathlib
import re
import sys

from isaaclab.utils.vscode import build_extra_paths, resolve_isaacsim_dir, write_pyright_config

PROJECT_DIR = pathlib.Path(__file__).parents[2]
"""Path to the repository or generated project's root directory."""


def overwrite_default_python_interpreter(settings: str, isaacsim_dir: pathlib.Path | None) -> str:
    """Set the editor's default Python interpreter.

    Args:
        settings: VS Code settings template.
        isaacsim_dir: Isaac Sim installation directory, or None.

    Returns:
        Settings with the interpreter path updated.
    """
    python_exe = pathlib.Path(sys.executable)
    if "kit/python/bin/python3" in python_exe.as_posix() and isaacsim_dir is not None:
        wrapper = isaacsim_dir / "python.sh"
        if wrapper.is_file():
            python_exe = wrapper
    return re.sub(
        r'"python\.defaultInterpreterPath": ".*?"',
        f'"python.defaultInterpreterPath": "{python_exe.as_posix()}"',
        settings,
        flags=re.DOTALL,
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--isaac_path", help="Absolute path to the Isaac Sim installation.")
    args = parser.parse_args()

    try:
        isaacsim_dir = resolve_isaacsim_dir(PROJECT_DIR, args.isaac_path)
    except ValueError as error:
        parser.error(str(error))
    write_pyright_config(PROJECT_DIR, build_extra_paths(PROJECT_DIR, isaacsim_dir))

    settings_template = PROJECT_DIR / ".vscode" / "tools" / "settings.template.json"
    if not settings_template.is_file():
        raise FileNotFoundError(f"Could not find the VS Code settings template: {settings_template}")
    settings = overwrite_default_python_interpreter(settings_template.read_text(encoding="utf-8"), isaacsim_dir)
    header = (
        "// This file is automatically generated by setup_vscode.py.\n"
        "// Do not edit this file directly.\n"
        f"// Generated from: {settings_template}\n"
    )
    (PROJECT_DIR / ".vscode" / "settings.json").write_text(header + settings, encoding="utf-8")

    launch_file = PROJECT_DIR / ".vscode" / "launch.json"
    launch_template = PROJECT_DIR / ".vscode" / "tools" / "launch.template.json"
    if not launch_file.exists():
        launch_header = header.replace(str(settings_template), str(launch_template))
        launch_file.write_text(launch_header + launch_template.read_text(encoding="utf-8"), encoding="utf-8")


if __name__ == "__main__":
    main()
