# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

__all__ = [
    "define_deformable_body_properties",
    "modify_deformable_body_properties",
    "ArticulationRootPropertiesCfg",
    "CollisionPropertiesCfg",
    "ConvexDecompositionPropertiesCfg",
    "ConvexHullPropertiesCfg",
    "DeformableBodyPropertiesCfg",
    "FixedTendonPropertiesCfg",
    "JointDrivePropertiesCfg",
    "MeshCollisionPropertiesCfg",
    "OmniPhysicsDeformableBodyPropertiesCfg",
    "PhysxArticulationRootPropertiesCfg",
    "PhysxCollisionPropertiesCfg",
    "PhysxConvexDecompositionPropertiesCfg",
    "PhysxConvexHullPropertiesCfg",
    "PhysxDeformableBodyPropertiesCfg",
    "PhysxDeformableCollisionPropertiesCfg",
    "PhysxFixedTendonPropertiesCfg",
    "PhysxJointDrivePropertiesCfg",
    "PhysxRigidBodyPropertiesCfg",
    "PhysxSDFMeshPropertiesCfg",
    "PhysxSpatialTendonPropertiesCfg",
    "PhysxTriangleMeshPropertiesCfg",
    "PhysxTriangleMeshSimplificationPropertiesCfg",
    "RigidBodyPropertiesCfg",
    "SDFMeshPropertiesCfg",
    "SpatialTendonPropertiesCfg",
    "TriangleMeshPropertiesCfg",
    "TriangleMeshSimplificationPropertiesCfg",
]

from .schemas import (
    define_deformable_body_properties,
    modify_deformable_body_properties,
)
from .schemas_cfg import (
    ArticulationRootPropertiesCfg,
    CollisionPropertiesCfg,
    ConvexDecompositionPropertiesCfg,
    ConvexHullPropertiesCfg,
    DeformableBodyPropertiesCfg,
    FixedTendonPropertiesCfg,
    JointDrivePropertiesCfg,
    MeshCollisionPropertiesCfg,
    OmniPhysicsDeformableBodyPropertiesCfg,
    PhysxArticulationRootPropertiesCfg,
    PhysxCollisionPropertiesCfg,
    PhysxConvexDecompositionPropertiesCfg,
    PhysxConvexHullPropertiesCfg,
    PhysxDeformableBodyPropertiesCfg,
    PhysxDeformableCollisionPropertiesCfg,
    PhysxFixedTendonPropertiesCfg,
    PhysxJointDrivePropertiesCfg,
    PhysxRigidBodyPropertiesCfg,
    PhysxSDFMeshPropertiesCfg,
    PhysxSpatialTendonPropertiesCfg,
    PhysxTriangleMeshPropertiesCfg,
    PhysxTriangleMeshSimplificationPropertiesCfg,
    RigidBodyPropertiesCfg,
    SDFMeshPropertiesCfg,
    SpatialTendonPropertiesCfg,
    TriangleMeshPropertiesCfg,
    TriangleMeshSimplificationPropertiesCfg,
)
