# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Image generation from per-view control sequences, applied as a modifier."""

from __future__ import annotations

import math
from collections.abc import Sequence
from typing import TYPE_CHECKING

import torch

from isaaclab.sim import SimulationContext
from isaaclab.utils import instantiate
from isaaclab.utils.modifiers import ModifierBase

if TYPE_CHECKING:
    from .backend import ImageTransferModel
    from .modifier_cfg import ImageTransferModifierCfg

_SEED_MODULUS = 2**31


class ImageTransferModifier(ModifierBase):
    """Queue uint8 controls per view and publish images generated by an application-owned model.

    Each call queues one control per view. Once every view has a complete chunk (``initial_frames``
    at the start of an episode, ``update_frames`` afterwards), the stream generates one chunk per view
    and the output takes the last generated image. The output holds that image until the next chunk.

    A stream error or invalid result marks the modifier as failed: the stream may already have advanced,
    so it is never retried against the same queues. Recreate the camera or modifier instead.
    """

    def __init__(self, cfg: ImageTransferModifierCfg, data_dim: tuple[int, ...], device: str):
        """Open a generation stream for the views of ``data_dim``.

        Args:
            cfg: Modifier configuration.
            data_dim: Control shape ``(N, H, W, 3)``.
            device: Device of the controls and output.

        Raises:
            ValueError: If the control shape or the chunk settings are invalid.
        """
        super().__init__(cfg, data_dim, device)
        _validate(cfg, data_dim)
        num_views = data_dim[0]
        sim = SimulationContext.instance()
        # The simulation owns shared models; a model built without one belongs to this modifier.
        self._owned_model: ImageTransferModel | None = None
        if sim is not None:
            model = sim.get_or_create_backend(cfg.backend)
        else:
            model = self._owned_model = instantiate(cfg.backend)
        self._seeds = tuple((cfg.seed + row) % _SEED_MODULUS for row in range(num_views))
        self._stream = model.open_stream(num_views, self._seeds)
        self._pending: list[list[torch.Tensor]] = [[] for _ in range(num_views)]
        self._fresh = [True] * num_views
        self._episodes = [0] * num_views
        self._reset_rows: set[int] = set()
        self._started = False
        self._failed = False
        self._closed = False
        self._output = torch.zeros(data_dim, dtype=torch.uint8, device=device)

    def __call__(self, data: torch.Tensor) -> torch.Tensor:
        """Queue one control per view and generate a chunk when every view has one.

        Args:
            data: Controls of shape ``(N, H, W, 3)``, dtype uint8.

        Returns:
            The latest generated images, shape ``(N, H, W, 3)``. The buffer is reused by later calls.

        Raises:
            RuntimeError: If the modifier is closed or failed, or a view's queue is full.
            ValueError: If the controls or the generated images have the wrong shape or type.
        """
        if self._closed or self._failed:
            raise RuntimeError("Image transfer modifier is closed or failed; recreate it.")
        if tuple(data.shape) != self._data_dim or data.dtype != torch.uint8:
            raise ValueError(f"Image transfer controls must be uint8 with shape {self._data_dim}.")
        cfg = self._cfg
        if any(len(queue) >= cfg.max_pending_frames for queue in self._pending):
            raise RuntimeError("Image transfer control queue is full; views must reset and advance compatibly.")
        with torch.no_grad():
            for row, queue in enumerate(self._pending):
                queue.append(data[row].clone())
            counts = [cfg.initial_frames if fresh else cfg.update_frames for fresh in self._fresh]
            if not all(len(queue) >= count for queue, count in zip(self._pending, counts)):
                return self._output
            controls = [torch.stack(queue[:count]) for queue, count in zip(self._pending, counts)]
            resets = tuple(sorted(self._reset_rows)) if self._started else ()
            num_views = len(self._pending)
            seeds = tuple((self._seeds[row] + self._episodes[row] * num_views) % _SEED_MODULUS for row in resets)
            try:
                generated = self._stream.step(controls, resets, seeds)
                if len(generated) != num_views:
                    raise ValueError("Image transfer returned the wrong number of views.")
                for images, count in zip(generated, counts):
                    if tuple(images.shape) != (count, *self._data_dim[1:]) or images.dtype != torch.uint8:
                        raise ValueError("Image transfer must return uint8 THWC RGB matching each control chunk.")
            except Exception:
                self._failed = True
                raise
            # Publish only after the whole result is validated.
            for row, (images, count) in enumerate(zip(generated, counts)):
                self._output[row].copy_(images[-1])
                del self._pending[row][:count]
                self._fresh[row] = False
            self._started = True
            self._reset_rows.clear()
        return self._output

    def reset(self, env_ids: Sequence[int] | torch.Tensor | None = None):
        """Discard the queued controls and episode state of the selected views.

        Args:
            env_ids: Views to reset. Defaults to None, which resets all views.
        """
        if self._closed:
            return
        if env_ids is None:
            rows = range(len(self._pending))
        else:
            rows = env_ids.tolist() if isinstance(env_ids, torch.Tensor) else list(env_ids)
        for row in rows:
            self._pending[row].clear()
            self._fresh[row] = True
            # A reset before the first generation has no episode to discard.
            if self._started:
                self._episodes[row] += 1
                self._reset_rows.add(row)
            self._output[row].zero_()

    def close(self) -> None:
        """Close the stream and, without a simulation context, the model."""
        if self._closed:
            return
        self._closed = True
        self._pending = [[] for _ in self._pending]
        try:
            self._stream.close()
        finally:
            if self._owned_model is not None:
                self._owned_model.close()


def depth_to_control(data: torch.Tensor, near: float = 0.1, far: float = 10.0) -> torch.Tensor:
    """Map metric depth to uint8 three-channel controls.

    Hits at ``near`` become white and hits at ``far`` black. Missing, nonfinite, and nonpositive
    depth becomes black.

    Args:
        data: Depth [m] of shape ``(N, H, W, 1)``.
        near: White depth endpoint [m].
        far: Black depth endpoint [m].

    Returns:
        Controls of shape ``(N, H, W, 3)``, dtype uint8.
    """
    if not (math.isfinite(near) and math.isfinite(far) and 0 < near < far):
        raise ValueError("Depth bounds must be finite and satisfy 0 < near < far.")
    valid = torch.isfinite(data) & (data > 0)
    metric = torch.where(valid, data, far)
    pixels = ((far - metric) / (far - near)).clamp(0, 1).mul(255).round().to(torch.uint8)
    return pixels.expand(*pixels.shape[:-1], 3)


def srgb_to_linear(data: torch.Tensor) -> torch.Tensor:
    """Approximate scene-linear color from display sRGB, for example before PPISP.

    The inverse sRGB transfer function does not recover scene HDR, exposure, or a baked camera
    response. Use the renderer's ``rgb_radiance`` for calibrated camera processing.

    Args:
        data: sRGB of shape ``(N, H, W, 3)``, dtype uint8.

    Returns:
        Linear color of shape ``(N, H, W, 3)``, dtype float32.
    """
    value = data.to(torch.float32) / 255.0
    return torch.where(value > 0.04045, ((value + 0.055) / 1.055) ** 2.4, value / 12.92)


def _validate(cfg: ImageTransferModifierCfg, data_dim: tuple[int, ...]) -> None:
    if len(data_dim) != 4 or data_dim[-1] != 3:
        raise ValueError(f"Image transfer expects controls with shape (N, H, W, 3), got {data_dim}.")
    sizes = (cfg.initial_frames, cfg.update_frames, cfg.max_pending_frames)
    if any(type(value) is not int or value < 1 for value in sizes):
        raise ValueError("Chunk sizes and queue capacity must be positive integers.")
    if cfg.max_pending_frames < max(cfg.initial_frames, cfg.update_frames):
        raise ValueError("Queue capacity must accommodate both configured chunk sizes.")
