# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Sweep mesh density, object stiffness, or grip force and record the grasped width.

Companion to ``grasp_determinism.py``. Same protocol -- the end-effector holds one
constant pose and only the gripper is actuated -- but here one process walks a list
of parameter values, rebuilding the environment for each, and writes a CSV.

The deformable's tetrahedral mesh is normally regenerated by fTetWild at every
spawn and comes out different every time (node counts of 61/66/67/70/74 were
observed for the same cuboid), which swamps any parameter effect. This script
monkeypatches ``pytetwild.tetrahedralize`` with a disk-cached wrapper keyed on the
input surface and the requested edge length, so a given ``edge_length_fac`` always
yields a byte-identical mesh -- across configs and across processes. That makes
"fixed mesh" actually fixed, and makes ``--mode mesh`` a controlled study of
resolution rather than of fTetWild's RNG.

Modes:
  mesh       vary ``edge_length_fac`` (mesh resolution) at fixed material and force
  stiffness  vary Young's modulus at fixed mesh and force  -> Hooke: delta ~ 1/E
  force      vary the finger effort cap at fixed mesh and material -> Hooke: delta ~ F

.. code-block:: bash

    isaaclab.bat -p scripts/environments/state_machine/grasp_sweep.py --mode mesh \
        --values 0.30,0.22,0.16,0.12,0.10,0.08,0.06 --grip_effort 40
"""

import argparse

from isaaclab.app import AppLauncher

parser = argparse.ArgumentParser(description="Parameter sweeps for the Newton soft-body grasp.")
parser.add_argument("--mode", type=str, required=True, choices=["mesh", "stiffness", "force"], help="Swept quantity.")
parser.add_argument("--values", type=str, required=True, help="Comma-separated values for the swept quantity.")
parser.add_argument("--grip_effort", type=float, default=40.0, help="Finger effort cap [N] (fixed unless mode=force).")
parser.add_argument(
    "--grip_stiffness",
    type=float,
    default=2e4,
    help=(
        "Finger joint stiffness. Must be high enough that the effort cap actually binds, otherwise the applied"
        " grip force is set by the PD spring (stiffness x error) and varies with the object instead of being"
        " controlled. 0 keeps the env default of 1000."
    ),
)
parser.add_argument("--youngs", type=float, default=8e4, help="Young's modulus [Pa] (fixed unless mode=stiffness).")
parser.add_argument("--poissons", type=float, default=0.25, help="Poisson's ratio [-].")
parser.add_argument(
    "--size",
    type=str,
    default="0.05,0.05,0.05",
    help=(
        "Deformable box size 'x,y,z' [m]. Defaults to a cube rather than the task's 0.3 m bar: the long bar yaws"
        " under the fingers, which inflates any width measure and masks the material response. A cube also gives a"
        " well-defined contact area for the analytic Hooke prediction."
    ),
)
parser.add_argument("--edge_fac", type=float, default=0.10, help="Tet edge length factor (fixed unless mode=mesh).")
parser.add_argument(
    "--arm_stiffness",
    type=float,
    default=800.0,
    help=(
        "Franka arm joint stiffness (0 keeps the env default ~80). The default is far too soft to place the TCP"
        " accurately: the residual IK error is centimetres, which a 0.3 m bar forgives but a 0.05 m cube does not"
        " -- the fingers close on empty air."
    ),
)
parser.add_argument("--arm_damping", type=float, default=80.0, help="Franka arm joint damping (0 keeps default).")
parser.add_argument("--pregrasp_steps", type=int, default=130, help="Steps above the object before descending.")
parser.add_argument("--pregrasp_z", type=float, default=0.1, help="Pre-grasp height above the object COM [m].")
parser.add_argument("--settle_steps", type=int, default=140, help="Steps descending with the gripper open.")
parser.add_argument("--squeeze_steps", type=int, default=300, help="Steps with the gripper closing.")
parser.add_argument("--measure_steps", type=int, default=60, help="Trailing squeeze steps averaged.")
parser.add_argument("--out", type=str, default="", help="CSV output path (default: sweeps/<mode>.csv).")
AppLauncher.add_app_launcher_args(parser)
args_cli = parser.parse_args()

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

from isaacsim.core.experimental.utils.app import enable_extension

enable_extension("omni.usd.metrics.assembler.ui", enabled=False)

import hashlib
import os

import gymnasium as gym
import numpy as np
import torch

import isaaclab_tasks  # noqa: F401
from isaaclab_tasks.utils.hydra import resolve_presets
from isaaclab_tasks.utils.parse_cfg import load_cfg_from_registry

TASK = "Isaac-Lift-Soft-Franka-v0"
GRIPPER_OPEN = 1.0
GRIPPER_CLOSE = -1.0
REST_WIDTH_Y = 0.05  # spawned cuboid is 0.3 x 0.05 x 0.05; fingers close along world y

CACHE_DIR = os.path.join("C:\\", "isaac_soft", ".tetcache")


##
# Deterministic tetrahedralisation
##

_tet_state = {"edge_fac": args_cli.edge_fac}


def _install_tet_cache():
    """Make fTetWild's output reproducible by caching it on disk, keyed by surface + edge length."""
    import pytetwild

    original = pytetwild.tetrahedralize
    os.makedirs(CACHE_DIR, exist_ok=True)

    def cached(vertices, faces, **kwargs):
        kwargs["edge_length_fac"] = _tet_state["edge_fac"]
        h = hashlib.sha1()
        h.update(np.ascontiguousarray(vertices, dtype=np.float64).tobytes())
        h.update(np.ascontiguousarray(faces, dtype=np.int32).tobytes())
        h.update(repr(sorted(kwargs.items())).encode())
        path = os.path.join(CACHE_DIR, f"tet_{h.hexdigest()[:16]}.npz")
        if os.path.exists(path):
            d = np.load(path)
            return d["points"], d["indices"]
        points, indices = original(vertices, faces, **kwargs)
        np.savez(path, points=points, indices=indices)
        return points, indices

    pytetwild.tetrahedralize = cached


_install_tet_cache()


def lame(youngs: float, poissons: float) -> tuple[float, float]:
    """Lame parameters ``(k_mu, k_lambda)`` [Pa] from Young's modulus and Poisson's ratio."""
    k_mu = youngs / (2.0 * (1.0 + poissons))
    k_lambda = youngs * poissons / ((1.0 + poissons) * (1.0 - 2.0 * poissons))
    return k_mu, k_lambda


def run_one(value: float) -> dict | None:
    """Build the env for one sweep point, squeeze, and return the measurements."""
    youngs = value if args_cli.mode == "stiffness" else args_cli.youngs
    effort = value if args_cli.mode == "force" else args_cli.grip_effort
    _tet_state["edge_fac"] = value if args_cli.mode == "mesh" else args_cli.edge_fac

    cfg = load_cfg_from_registry(TASK, "env_cfg_entry_point")
    cfg = resolve_presets(cfg, selected=[])  # Newton (MJWarp rigid + VBD soft)
    cfg.sim.device = args_cli.device
    cfg.scene.num_envs = 1
    cfg.seed = 0

    trial_steps = args_cli.pregrasp_steps + args_cli.settle_steps + args_cli.squeeze_steps
    cfg.episode_length_s = max(30.0, (trial_steps + 60) * cfg.sim.dt * cfg.decimation)

    # fixed initial conditions
    cfg.events.reset_robot_joints.params["position_range"] = (1.0, 1.0)
    cfg.events.reset_deformable.params["position_range"] = {"x": (0.0, 0.0), "y": (0.0, 0.0), "z": (0.0, 0.0)}

    # object geometry
    size = tuple(float(s) for s in args_cli.size.split(","))
    cfg.scene.deformable.spawn.size = size

    # material + grasp force
    k_mu, k_lambda = lame(youngs, args_cli.poissons)
    material = cfg.scene.deformable.spawn.physics_material
    material.k_mu = k_mu
    material.k_lambda = k_lambda
    cfg.scene.robot.actuators["panda_hand"].effort_limit_sim = effort
    if args_cli.grip_stiffness > 0.0:
        cfg.scene.robot.actuators["panda_hand"].stiffness = args_cli.grip_stiffness

    # stiffen the arm so the TCP actually lands on the object
    for name, act in cfg.scene.robot.actuators.items():
        if name == "panda_hand":
            continue
        if args_cli.arm_stiffness > 0.0:
            act.stiffness = args_cli.arm_stiffness
        if args_cli.arm_damping > 0.0:
            act.damping = args_cli.arm_damping

    env = gym.make(TASK, cfg=cfg, render_mode=None)
    try:
        device = env.unwrapped.device
        robot = env.unwrapped.scene["robot"]
        finger_ids, _ = robot.find_joints("panda_finger.*")
        deformable = env.unwrapped.scene["deformable"]

        env.reset(seed=0)
        nodes = int(deformable.data.nodal_pos_w.torch.shape[1])

        obj_com = deformable.data.root_pos_w.torch.clone()
        obj_com_local = obj_com - env.unwrapped.scene.env_origins
        actions = torch.zeros((1, env.unwrapped.action_space.shape[-1]), device=device)
        actions[:, 0:3] = obj_com_local
        actions[:, 3] = 1.0
        actions[:, -1] = GRIPPER_OPEN

        actions[:, 2] = obj_com_local[:, 2] + args_cli.pregrasp_z
        for _ in range(args_cli.pregrasp_steps):
            env.step(actions)

        actions[:, 2] = obj_com_local[:, 2]
        for _ in range(args_cli.settle_steps):
            env.step(actions)
        open_gap = float(robot.data.joint_pos[0, finger_ids].sum().item())

        # did the TCP actually land on the object? a miss here means the fingers close on air
        ee_w = env.unwrapped.scene["ee_frame"].data.target_pos_w.torch[0, 0, :]
        obj_now = deformable.data.root_pos_w.torch[0]
        miss = (ee_w - obj_now).abs()
        miss_x, miss_y, miss_z = (float(miss[0]), float(miss[1]), float(miss[2]))
        obj_moved = float((obj_now - obj_com[0]).norm().item())

        actions[:, -1] = GRIPPER_CLOSE
        gaps, efforts = [], []
        measure_from = args_cli.squeeze_steps - args_cli.measure_steps
        for k in range(args_cli.squeeze_steps):
            env.step(actions)
            if k >= measure_from:
                gaps.append(float(robot.data.joint_pos[0, finger_ids].sum().item()))
                try:
                    efforts.append(float(robot.data.applied_torque[0, finger_ids].abs().max().item()))
                except Exception:
                    efforts.append(float("nan"))

        gap = sum(gaps) / len(gaps)
        gap_drift = abs(gaps[-1] - gaps[0])
        applied = sum(efforts) / len(efforts)
        row = {
            "value": value,
            "mode": args_cli.mode,
            "nodes": nodes,
            "edge_fac": _tet_state["edge_fac"],
            "youngs": youngs,
            "effort_cap": effort,
            "grip_stiffness": args_cli.grip_stiffness,
            "applied_force": applied,
            "saturated": abs(applied - effort) < 0.05 * effort,
            "open_gap": open_gap,
            "gap": gap,
            "gap_drift": gap_drift,
            "compression": size[1] - gap,
            "size_y": size[1],
            "miss_x": miss_x,
            "miss_y": miss_y,
            "miss_z": miss_z,
            "obj_moved": obj_moved,
            "grasped": gap > 0.2 * size[1],  # gap collapsing to ~0 means the fingers closed on air
            # analytic uniaxial Hooke prediction: delta = F * L / (E * A)
            "hooke_pred": applied * size[1] / (youngs * size[0] * size[2]),
        }
        print(
            f"[SWEEP] mode={args_cli.mode} value={value:g} nodes={nodes} E={youngs:g} "
            f"cap={effort:g} applied={applied:.3f} open_gap={open_gap:.6f} gap={gap:.6f} "
            f"compression={row['compression']:.6f} hooke_pred={row['hooke_pred']:.6f} drift={gap_drift:.2e} "
            f"grasped={row['grasped']} miss=({miss_x:.4f},{miss_y:.4f},{miss_z:.4f}) obj_moved={obj_moved:.4f}",
            flush=True,
        )
        return row
    finally:
        env.close()


def main():
    values = [float(v) for v in args_cli.values.split(",") if v.strip()]
    out = args_cli.out or os.path.join("C:\\", "isaac_soft", "sweeps", f"{args_cli.mode}.csv")
    os.makedirs(os.path.dirname(out), exist_ok=True)

    print(f"[SWEEP] START mode={args_cli.mode} values={values} out={out}", flush=True)
    rows = []
    for v in values:
        try:
            row = run_one(v)
            if row:
                rows.append(row)
        except Exception as exc:  # keep the sweep alive if one point blows up
            print(f"[SWEEP] FAILED value={v}: {type(exc).__name__}: {exc}", flush=True)

        if rows:  # rewrite after every point so a crash still leaves usable data
            cols = list(rows[0].keys())
            with open(out, "w", encoding="utf-8") as f:
                f.write(",".join(cols) + "\n")
                for r in rows:
                    f.write(",".join(str(r[c]) for c in cols) + "\n")

    print(f"[SWEEP] DONE points={len(rows)} out={out}", flush=True)


if __name__ == "__main__":
    main()
    simulation_app.close()
