# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""IsaacLab re-exports of ovphysx TensorType with short backward-compat aliases.

Import TensorType directly for new code:
    from ovphysx.types import TensorType

Or use the module-level short aliases (existing code pattern):
    import isaaclab_ovphysx.tensor_types as TT
    TT.DOF_STIFFNESS  # resolves to TensorType.ARTICULATION_DOF_STIFFNESS

ovphysx.types is pure Python with zero native dependencies, so this module is
always safe to import regardless of USD state or native library loading.
"""

from ovphysx.types import TensorType  # noqa: F401 — re-exported for new code

_TT = TensorType  # shorter reference for alias block

# Short aliases — existing code using `TT.DOF_STIFFNESS` etc. continues to work.
# All values are IntEnum members (== plain ints) of TensorType.
ROOT_POSE                    = _TT.ARTICULATION_ROOT_POSE
ROOT_VELOCITY                = _TT.ARTICULATION_ROOT_VELOCITY
LINK_POSE                    = _TT.ARTICULATION_LINK_POSE
LINK_VELOCITY                = _TT.ARTICULATION_LINK_VELOCITY
LINK_ACCELERATION            = _TT.ARTICULATION_LINK_ACCELERATION
DOF_POSITION                 = _TT.ARTICULATION_DOF_POSITION
DOF_VELOCITY                 = _TT.ARTICULATION_DOF_VELOCITY
DOF_POSITION_TARGET          = _TT.ARTICULATION_DOF_POSITION_TARGET
DOF_VELOCITY_TARGET          = _TT.ARTICULATION_DOF_VELOCITY_TARGET
DOF_ACTUATION_FORCE          = _TT.ARTICULATION_DOF_ACTUATION_FORCE
DOF_STIFFNESS                = _TT.ARTICULATION_DOF_STIFFNESS
DOF_DAMPING                  = _TT.ARTICULATION_DOF_DAMPING
DOF_LIMIT                    = _TT.ARTICULATION_DOF_LIMIT
DOF_MAX_VELOCITY             = _TT.ARTICULATION_DOF_MAX_VELOCITY
DOF_MAX_FORCE                = _TT.ARTICULATION_DOF_MAX_FORCE
DOF_ARMATURE                 = _TT.ARTICULATION_DOF_ARMATURE
DOF_FRICTION_PROPERTIES      = _TT.ARTICULATION_DOF_FRICTION_PROPERTIES
LINK_WRENCH                  = _TT.ARTICULATION_LINK_WRENCH
BODY_MASS                    = _TT.ARTICULATION_BODY_MASS
BODY_COM_POSE                = _TT.ARTICULATION_BODY_COM_POSE
BODY_INERTIA                 = _TT.ARTICULATION_BODY_INERTIA
BODY_INV_MASS                = _TT.ARTICULATION_BODY_INV_MASS
BODY_INV_INERTIA             = _TT.ARTICULATION_BODY_INV_INERTIA
JACOBIAN                     = _TT.ARTICULATION_JACOBIAN
MASS_MATRIX                  = _TT.ARTICULATION_MASS_MATRIX
CORIOLIS                     = _TT.ARTICULATION_CORIOLIS_AND_CENTRIFUGAL_FORCE
GRAVITY_FORCE                = _TT.ARTICULATION_GRAVITY_FORCE
LINK_INCOMING_JOINT_FORCE    = _TT.ARTICULATION_LINK_INCOMING_JOINT_FORCE
DOF_PROJECTED_JOINT_FORCE    = _TT.ARTICULATION_DOF_PROJECTED_JOINT_FORCE
FIXED_TENDON_STIFFNESS       = _TT.ARTICULATION_FIXED_TENDON_STIFFNESS
FIXED_TENDON_DAMPING         = _TT.ARTICULATION_FIXED_TENDON_DAMPING
FIXED_TENDON_LIMIT_STIFFNESS = _TT.ARTICULATION_FIXED_TENDON_LIMIT_STIFFNESS
FIXED_TENDON_LIMIT           = _TT.ARTICULATION_FIXED_TENDON_LIMIT
FIXED_TENDON_REST_LENGTH     = _TT.ARTICULATION_FIXED_TENDON_REST_LENGTH
FIXED_TENDON_OFFSET          = _TT.ARTICULATION_FIXED_TENDON_OFFSET
SPATIAL_TENDON_STIFFNESS     = _TT.ARTICULATION_SPATIAL_TENDON_STIFFNESS
SPATIAL_TENDON_DAMPING       = _TT.ARTICULATION_SPATIAL_TENDON_DAMPING
SPATIAL_TENDON_LIMIT_STIFFNESS = _TT.ARTICULATION_SPATIAL_TENDON_LIMIT_STIFFNESS
SPATIAL_TENDON_OFFSET        = _TT.ARTICULATION_SPATIAL_TENDON_OFFSET

# DOF/body property tensor types are CPU-resident even in GPU simulations.
# Write helpers check this set to route data through CPU, not self._device.
_CPU_ONLY_TYPES: frozenset[TensorType] = frozenset({
    DOF_STIFFNESS, DOF_DAMPING, DOF_LIMIT, DOF_MAX_VELOCITY, DOF_MAX_FORCE,
    DOF_ARMATURE, DOF_FRICTION_PROPERTIES,
    BODY_MASS, BODY_COM_POSE, BODY_INERTIA, BODY_INV_MASS, BODY_INV_INERTIA,
    FIXED_TENDON_STIFFNESS, FIXED_TENDON_DAMPING, FIXED_TENDON_LIMIT_STIFFNESS,
    FIXED_TENDON_LIMIT, FIXED_TENDON_REST_LENGTH, FIXED_TENDON_OFFSET,
    SPATIAL_TENDON_STIFFNESS, SPATIAL_TENDON_DAMPING,
    SPATIAL_TENDON_LIMIT_STIFFNESS, SPATIAL_TENDON_OFFSET,
})
