# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Utilities for generating editor import paths for Isaac Lab projects."""

import importlib.metadata
import importlib.util
import json
import os
import pathlib
import platform
import re
import subprocess
import sys

_DEFAULT_VSCODE_SETTINGS_TEMPLATE = """
{
    "editor.rulers": [120],

    "python.languageServer": "Pylance",
    "python.jediEnabled": false,
    "python.defaultInterpreterPath": "",

    "python.formatting.provider": "black",
    "python.formatting.blackArgs": ["--line-length", "120"],

    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,

    "[python]": {
        "editor.tabSize": 4
    }
}
"""


def setup_editor(project_dir: pathlib.Path, isaac_path: str | None = None, verbose: bool = False) -> None:
    """Generate editor settings and Pyright import paths for a project.

    Args:
        project_dir: Project root where the editor configuration is written.
        isaac_path: Explicit Isaac Sim installation path, or None to discover it.
        verbose: Whether to print every generated Pyright search path.
    """
    isaacsim_dir = resolve_isaacsim_dir(project_dir, isaac_path)
    extra_paths = build_extra_paths(project_dir, isaacsim_dir)
    write_pyright_config(project_dir, extra_paths)
    if verbose:
        for path in extra_paths:
            print(f"Registered Pyright search path: {path}")

    vscode_dir = project_dir / ".vscode"
    settings_template = vscode_dir / "tools" / "settings.template.json"
    if settings_template.is_file():
        settings = settings_template.read_text(encoding="utf-8")
        settings_source = settings_template.as_posix()
    else:
        settings = _DEFAULT_VSCODE_SETTINGS_TEMPLATE
        settings_source = "Isaac Lab defaults"
    settings = _overwrite_default_python_interpreter(settings, isaacsim_dir)

    vscode_dir.mkdir(parents=True, exist_ok=True)
    header = (
        "// This file is automatically generated by `isaaclab --editor`.\n"
        "// Do not edit this file directly.\n"
        f"// Generated from: {settings_source}\n"
    )
    settings_path = vscode_dir / "settings.json"
    settings_path.write_text(header + settings, encoding="utf-8")

    launch_path = vscode_dir / "launch.json"
    launch_template = vscode_dir / "tools" / "launch.template.json"
    if not launch_path.exists() and launch_template.is_file():
        launch_header = header.replace(settings_source, launch_template.as_posix())
        launch_path.write_text(launch_header + launch_template.read_text(encoding="utf-8"), encoding="utf-8")

    print(f"Editor settings generated at {settings_path}")
    print(f"Pyright configuration generated at {project_dir / 'pyrightconfig.json'}")

    # Desktop icon integration is a convenience, not something that should block the rest of
    # this command -- an unwritable home directory or unreadable kit file shouldn't turn a
    # successful editor-settings run into a hard crash.
    try:
        setup_desktop_entry(project_dir)
    except OSError as error:
        print(f"[WARN] Skipped desktop entry generation: {error}")


def setup_desktop_entry(project_dir: pathlib.Path) -> None:
    """Generate a Linux desktop entry so the taskbar shows the Isaac Sim icon, not a generic one.

    Kit's window manager class (``WM_CLASS``) is composed from the ``[settings.app.window] title``
    and ``[settings.app] version`` values in ``apps/isaaclab.python.kit`` (for example
    ``"Isaac Lab 3.0.0"``), with no exposed setting to make it version-independent: overriding
    ``/app/version`` to empty falls back to the raw Kit SDK build string instead of dropping the
    suffix. Most Linux desktop environments (GNOME included) resolve taskbar/dock icons by
    matching a running window's ``WM_CLASS`` against an installed ``.desktop`` file's
    ``StartupWMClass`` -- not from the window's own ``_NET_WM_ICON`` hint, which Kit does set
    correctly (confirmed with ``xprop``) but which most taskbars ignore for this purpose. Without
    a matching ``.desktop`` file, the desktop environment falls back to a generic icon.

    Because ``WM_CLASS`` embeds the app title and version, ``StartupWMClass`` here is read from
    the same ``apps/isaaclab.python.kit`` file rather than hardcoded, so it self-updates on every
    ``isaaclab --editor`` run. Requirement to track: if a future Isaac Lab release changes
    ``apps/isaaclab.python.kit``'s ``[settings.app.window] title`` or ``[settings.app] version``
    (or Kit changes how it composes ``WM_CLASS`` at all), this needs re-running -- there is no way
    to keep the ``.desktop`` file in sync automatically without that rerun, since the desktop
    entry is a static file, not a live setting.

    No-op on non-Linux platforms, or if the kit file or the Isaac Sim icon asset cannot be found;
    desktop icon integration is a convenience, not something that should block the rest of
    ``isaaclab --editor``.

    Args:
        project_dir: Project root, used to locate ``apps/isaaclab.python.kit``.
    """
    if platform.system() != "Linux":
        return

    kit_file = project_dir / "apps" / "isaaclab.python.kit"
    identity = _read_kit_window_identity(kit_file)
    if identity is None:
        return
    title, version = identity

    icon_path = _find_isaac_sim_icon()
    if icon_path is None:
        return

    applications_dir = pathlib.Path.home() / ".local" / "share" / "applications"
    applications_dir.mkdir(parents=True, exist_ok=True)
    desktop_path = applications_dir / "isaaclab.desktop"
    desktop_path.write_text(
        "[Desktop Entry]\n"
        "Version=1.0\n"
        "Type=Application\n"
        "Name=Isaac Lab\n"
        f"Exec={sys.executable} -m isaaclab\n"
        f"Icon={icon_path}\n"
        "Terminal=true\n"
        f"StartupWMClass={title} {version}\n",
        encoding="utf-8",
    )
    print(f"Desktop entry generated at {desktop_path}")


def _read_kit_window_identity(kit_file: pathlib.Path) -> tuple[str, str] | None:
    """Read the ``(title, version)`` pair Kit composes this app's ``WM_CLASS`` from.

    ``.kit`` files are TOML-like but redeclare the ``[settings]`` table across multiple
    sections (Kit's own parser merges them), which is invalid under strict TOML and rejects
    :mod:`tomllib`. Since only these two known scalars are needed, this scans lines under the
    exact ``[settings.app]`` and ``[settings.app.window]`` headers instead of parsing the whole
    file as TOML.

    Args:
        kit_file: Path to ``apps/isaaclab.python.kit``.

    Returns:
        The ``(title, version)`` pair, or None if the file or either value is missing.
    """
    if not kit_file.is_file():
        return None

    title: str | None = None
    version: str | None = None
    section = ""
    scalar_pattern = re.compile(r'^(\w+)\s*=\s*"([^"]*)"')
    for raw_line in kit_file.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1]
            continue
        match = scalar_pattern.match(line)
        if not match:
            continue
        key, value = match.groups()
        if section == "settings.app.window" and key == "title":
            title = value
        elif section == "settings.app" and key == "version":
            version = value

    if not title or not version:
        return None
    return title, version


def _find_isaac_sim_icon() -> pathlib.Path | None:
    """Locate the Isaac Sim icon asset shipped with the installed ``isaacsim`` package.

    Returns:
        Absolute path to the icon, or None if the ``isaacsim`` package is not installed or does
        not ship the expected asset.
    """
    spec = importlib.util.find_spec("isaacsim")
    if spec is None or not spec.submodule_search_locations:
        return None
    for location in spec.submodule_search_locations:
        icon_path = pathlib.Path(location) / "exts" / "isaacsim.simulation_app" / "data" / "omni.isaac.sim.png"
        if icon_path.is_file():
            return icon_path
    return None


def resolve_isaacsim_dir(project_dir: pathlib.Path, isaac_path: str | None = None) -> pathlib.Path | None:
    """Resolve the Isaac Sim installation directory.

    Args:
        project_dir: Project root containing an optional ``_isaac_sim`` link.
        isaac_path: Explicit Isaac Sim path, or None to discover the installation.

    Returns:
        The resolved installation directory, or None if Isaac Sim is unavailable.

    Raises:
        ValueError: If an explicit path does not identify a directory.
    """
    if isaac_path:
        explicit_path = pathlib.Path(isaac_path).expanduser()
        if not _is_isaacsim_dir(explicit_path):
            raise ValueError(f"Not an Isaac Sim directory (missing .vscode/settings.json): {explicit_path}")
        return explicit_path.resolve()

    env_path = os.environ.get("ISAAC_PATH")
    if env_path and _is_isaacsim_dir(pathlib.Path(env_path)):
        return pathlib.Path(env_path).resolve()

    probe = subprocess.run(
        [sys.executable, "-c", "import isaacsim, os; print(os.environ.get('ISAAC_PATH', ''))"],
        capture_output=True,
        text=True,
        check=False,
        stdin=subprocess.DEVNULL,
    )
    for line in reversed(probe.stdout.splitlines()):
        candidate = pathlib.Path(line.strip()).expanduser()
        if line.strip() and _is_isaacsim_dir(candidate):
            return candidate.resolve()

    fallback = project_dir / "_isaac_sim"
    return fallback.resolve() if _is_isaacsim_dir(fallback) else None


def read_isaacsim_extra_paths(isaacsim_dir: pathlib.Path | None) -> list[pathlib.Path]:
    """Read Isaac Sim's Python extension paths.

    Args:
        isaacsim_dir: Isaac Sim installation directory, or None.

    Returns:
        Absolute extension search paths.
    """
    if isaacsim_dir is None:
        print("[WARN] Isaac Sim was not found; simulator extension paths were not added.")
        return []

    settings_file = isaacsim_dir / ".vscode" / "settings.json"
    if not settings_file.is_file():
        print(f"[WARN] Isaac Sim VS Code settings were not found: {settings_file}")
        return []

    settings = settings_file.read_text(encoding="utf-8")
    match = re.search(r'"python\.analysis\.extraPaths"\s*:\s*\[(.*?)\]', settings, flags=re.DOTALL)
    if match is None:
        print(f"[WARN] python.analysis.extraPaths was not found in {settings_file}")
        return []

    paths = []
    for encoded_path in re.findall(r'"((?:\\.|[^"\\])*)"', match.group(1)):
        path = pathlib.Path(json.loads(f'"{encoded_path}"'))
        paths.append(path if path.is_absolute() else isaacsim_dir / path)
    return paths


def find_isaaclab_package_paths() -> list[pathlib.Path]:
    """Find Isaac Lab package roots visible to the active interpreter.

    Returns:
        Import roots for installed Isaac Lab packages.
    """
    paths = []
    package_names = sorted(name for name in importlib.metadata.packages_distributions() if name.startswith("isaaclab"))
    for package_name in package_names:
        spec = importlib.util.find_spec(package_name)
        if spec is None:
            continue
        if spec.submodule_search_locations:
            paths.extend(pathlib.Path(location).parent for location in spec.submodule_search_locations)
        elif spec.origin:
            paths.append(pathlib.Path(spec.origin).parent)
    return paths


def build_extra_paths(project_dir: pathlib.Path, isaacsim_dir: pathlib.Path | None) -> list[str]:
    """Build Pyright search paths for simulator, local, and installed packages.

    Args:
        project_dir: Project root used to discover local ``source/*`` or ``src`` packages.
        isaacsim_dir: Isaac Sim installation directory, or None.

    Returns:
        Deduplicated paths, relative to the project where practical.
    """
    paths = read_isaacsim_extra_paths(isaacsim_dir)
    source_dir = project_dir / "source"
    if source_dir.is_dir():
        paths.extend(path for path in sorted(source_dir.iterdir()) if path.is_dir())
    src_dir = project_dir / "src"
    if src_dir.is_dir():
        paths.append(src_dir)
    paths.extend(find_isaaclab_package_paths())

    formatted_paths = []
    seen = set()
    resolved_project_dir = project_dir.resolve()
    for path in paths:
        resolved_path = path.resolve()
        try:
            formatted_path = resolved_path.relative_to(resolved_project_dir).as_posix()
        except ValueError:
            formatted_path = resolved_path.as_posix()
        if formatted_path not in seen:
            seen.add(formatted_path)
            formatted_paths.append(formatted_path)
    return formatted_paths


def write_pyright_config(project_dir: pathlib.Path, extra_paths: list[str]):
    """Write a machine-local Pyright configuration that preserves project policy.

    Args:
        project_dir: Project root where the configuration is written.
        extra_paths: Additional import search paths.
    """
    config: dict[str, object] = {"extraPaths": extra_paths}
    if (project_dir / "pyproject.toml").is_file():
        config["extends"] = "./pyproject.toml"
    (project_dir / "pyrightconfig.json").write_text(json.dumps(config, indent=4) + "\n", encoding="utf-8")


def _is_isaacsim_dir(path: pathlib.Path) -> bool:
    """Check whether a directory contains the settings used for extension discovery."""
    return path.is_dir() and (path / ".vscode" / "settings.json").is_file()


def _overwrite_default_python_interpreter(settings: str, isaacsim_dir: pathlib.Path | None) -> str:
    """Set the editor's default Python interpreter."""
    python_exe = pathlib.Path(sys.executable)
    if "kit/python/bin/python3" in python_exe.as_posix() and isaacsim_dir is not None:
        wrapper = isaacsim_dir / "python.sh"
        if wrapper.is_file():
            python_exe = wrapper
    return re.sub(
        r'"python\.defaultInterpreterPath": ".*?"',
        f'"python.defaultInterpreterPath": "{python_exe.as_posix()}"',
        settings,
        flags=re.DOTALL,
    )
