# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Rasterize a static terrain mesh into a Newton heightfield collider.

Terrain meshes generated by :class:`isaaclab.terrains.TerrainImporter` reach the
Newton MuJoCo solver as a single large triangle mesh (hundreds of thousands of
vertices). MuJoCo's ``spec.compile`` runs its convex-hull / inertia / BVH path
over every face, which dominates solver-initialization time. When the terrain is
single-valued in Z (true for all locomotion terrains), an equivalent heightfield
collider at the same horizontal resolution collides identically on the
``mujoco_warp`` GPU pipeline while compiling roughly two orders of magnitude
faster.

This module rasterizes the mesh into a :class:`newton.Heightfield` by casting
rays straight down onto the surface on a regular grid.
"""

from __future__ import annotations

import newton
import numpy as np
import torch
import warp as wp

from isaaclab.utils.warp import raycast_mesh


def rasterize_mesh_to_heightfield(
    points: np.ndarray,
    faces: np.ndarray,
    resolution: float,
    *,
    device: str,
    max_cells_per_axis: int = 4096,
) -> tuple[newton.Heightfield, wp.transform]:
    """Rasterize a static terrain mesh into a Newton heightfield.

    The heightfield grid follows Newton's convention (see
    :class:`newton.Heightfield`): ``data[row, col]`` samples the surface at
    ``x = x_min + col * resolution`` and ``y = y_min + row * resolution``. The
    returned transform places the grid (centered at the origin) at the mesh's XY
    center; the solver applies ``min_z`` when creating the MuJoCo hfield geom.

    Args:
        points: Mesh vertices in world frame [m], shape ``[num_points, 3]``, float.
        faces: Triangle vertex indices, shape ``[num_faces, 3]``, int.
        resolution: Horizontal grid spacing [m]. Should match the terrain's
            ``horizontal_scale`` so collision fidelity is preserved.
        device: Torch/Warp device the ray-cast runs on (e.g. ``"cuda:0"``).
        max_cells_per_axis: Safety cap on grid rows/columns. If the mesh extent
            would exceed this, the resolution is coarsened to fit.

    Returns:
        A tuple ``(heightfield, xform)`` where ``heightfield`` is the Newton
        heightfield asset and ``xform`` is its world placement.
    """
    points = np.asarray(points, dtype=np.float32)
    faces = np.asarray(faces, dtype=np.int32).reshape(-1, 3)

    x_min, y_min, z_min = points.min(axis=0)
    x_max, y_max, z_max = points.max(axis=0)
    size_x = float(x_max - x_min)
    size_y = float(y_max - y_min)

    # Grid dimensions: col -> x, row -> y. Clamp to the safety cap.
    ncol = int(round(size_x / resolution)) + 1
    nrow = int(round(size_y / resolution)) + 1
    ncol = max(2, min(ncol, max_cells_per_axis))
    nrow = max(2, min(nrow, max_cells_per_axis))

    xs = np.linspace(x_min, x_max, ncol, dtype=np.float32)
    ys = np.linspace(y_min, y_max, nrow, dtype=np.float32)
    grid_x, grid_y = np.meshgrid(xs, ys)  # shape (nrow, ncol)

    # Cast rays straight down from above the mesh onto the surface. ``raycast_mesh``
    # reshapes its outputs to the ray grid's leading dims, so keep the (nrow, ncol)
    # grid shape and read the height grid back directly.
    z_start = float(z_max) + 1.0
    starts = np.stack([grid_x, grid_y, np.full_like(grid_x, z_start)], axis=-1)  # (nrow, ncol, 3)
    ray_starts = torch.as_tensor(starts, device=device)
    ray_dirs = torch.zeros_like(ray_starts)
    ray_dirs[..., 2] = -1.0

    wp_mesh = wp.Mesh(
        points=wp.array(points, dtype=wp.vec3, device=device),
        indices=wp.array(faces.reshape(-1), dtype=wp.int32, device=device),
    )
    hits, distances, _, _ = raycast_mesh(
        ray_starts, ray_dirs, wp_mesh, max_dist=z_start - float(z_min) + 1.0, return_distance=True
    )

    # Missed rays (holes/gaps) fall back to the floor so nothing collides there.
    heights = hits[..., 2].clone()  # (nrow, ncol)
    missed = torch.isinf(distances) | torch.isnan(distances)
    heights[missed] = float(z_min)
    data = heights.detach().cpu().numpy().astype(np.float32)

    min_z = float(data.min())
    max_z = float(data.max())
    heightfield = newton.Heightfield(
        data=data,
        nrow=nrow,
        ncol=ncol,
        hx=size_x * 0.5,
        hy=size_y * 0.5,
        min_z=min_z,
        max_z=max_z,
    )

    center_x = 0.5 * float(x_min + x_max)
    center_y = 0.5 * float(y_min + y_max)
    xform = wp.transform(wp.vec3(center_x, center_y, 0.0), wp.quat_identity())
    return heightfield, xform
