# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Sub-module with implementation of manager terms.

The functions can be provided to different managers that are responsible for the
different aspects of the MDP. These include the observation, reward, termination,
actions, events and curriculum managers.

The terms are defined under the ``envs`` module because they are used to define
the environment. However, they are not part of the environment directly, but
are used to define the environment through their managers.

"""

import lazy_loader as lazy

__getattr__, __dir__, __all__ = lazy.attach(
    __name__,
    submodules=["actions", "commands", "curriculums", "events", "observations", "recorders", "rewards", "terminations"],
    submod_attrs={
        "actions": [
            "AbsBinaryJointPositionActionCfg",
            "BinaryJointActionCfg",
            "BinaryJointPositionActionCfg",
            "BinaryJointVelocityActionCfg",
            "DifferentialInverseKinematicsActionCfg",
            "EMAJointPositionToLimitsActionCfg",
            "JointActionCfg",
            "JointEffortActionCfg",
            "JointPositionActionCfg",
            "JointPositionToLimitsActionCfg",
            "JointVelocityActionCfg",
            "NonHolonomicActionCfg",
            "OperationalSpaceControllerActionCfg",
            "RelativeJointPositionActionCfg",
            "SurfaceGripperBinaryActionCfg",
        ],
        "commands": [
            "NormalVelocityCommandCfg",
            "NullCommandCfg",
            "TerrainBasedPose2dCommandCfg",
            "UniformPose2dCommandCfg",
            "UniformPoseCommandCfg",
            "UniformVelocityCommandCfg",
            "NullCommand",
            "TerrainBasedPose2dCommand",
            "UniformPose2dCommand",
            "UniformPoseCommand",
            "NormalVelocityCommand",
            "UniformVelocityCommand",
        ],
        "curriculums": [
            "modify_env_param",
            "modify_reward_weight",
            "modify_term_cfg",
        ],
        "events": [
            "apply_external_force_torque",
            "push_by_setting_velocity",
            "randomize_actuator_gains",
            "randomize_fixed_tendon_parameters",
            "randomize_joint_parameters",
            "randomize_physics_scene_gravity",
            "randomize_rigid_body_collider_offsets",
            "randomize_rigid_body_com",
            "randomize_rigid_body_mass",
            "randomize_rigid_body_material",
            "randomize_rigid_body_scale",
            "randomize_visual_color",
            "randomize_visual_texture_material",
            "reset_joints_by_offset",
            "reset_joints_by_scale",
            "reset_nodal_state_uniform",
            "reset_root_state_from_terrain",
            "reset_root_state_uniform",
            "reset_root_state_with_random_orientation",
            "reset_scene_to_default",
        ],
        "observations": [
            "base_ang_vel",
            "base_lin_vel",
            "base_pos_z",
            "body_incoming_wrench",
            "body_pose_w",
            "body_projected_gravity_b",
            "current_time_s",
            "generated_commands",
            "height_scan",
            "image",
            "image_features",
            "imu_ang_vel",
            "imu_lin_acc",
            "imu_orientation",
            "imu_projected_gravity",
            "joint_effort",
            "joint_pos",
            "joint_pos_limit_normalized",
            "joint_pos_rel",
            "joint_vel",
            "joint_vel_rel",
            "last_action",
            "projected_gravity",
            "remaining_time_s",
            "root_ang_vel_w",
            "root_lin_vel_w",
            "root_pos_w",
            "root_quat_w",
        ],
        "recorders": [
            "ActionStateRecorderManagerCfg",
            "InitialStateRecorder",
            "InitialStateRecorderCfg",
            "PostStepProcessedActionsRecorder",
            "PostStepProcessedActionsRecorderCfg",
            "PostStepStatesRecorder",
            "PostStepStatesRecorderCfg",
            "PreStepActionsRecorder",
            "PreStepActionsRecorderCfg",
            "PreStepFlatPolicyObservationsRecorder",
            "PreStepFlatPolicyObservationsRecorderCfg",
        ],
        "rewards": [
            "action_l2",
            "action_rate_l2",
            "ang_vel_xy_l2",
            "applied_torque_limits",
            "base_height_l2",
            "body_lin_acc_l2",
            "contact_forces",
            "desired_contacts",
            "flat_orientation_l2",
            "is_alive",
            "is_terminated",
            "is_terminated_term",
            "joint_acc_l2",
            "joint_deviation_l1",
            "joint_pos_limits",
            "joint_torques_l2",
            "joint_vel_l1",
            "joint_vel_l2",
            "joint_vel_limits",
            "lin_vel_z_l2",
            "track_ang_vel_z_exp",
            "track_lin_vel_xy_exp",
            "undesired_contacts",
        ],
        "terminations": [
            "bad_orientation",
            "command_resample",
            "illegal_contact",
            "joint_effort_out_of_limit",
            "joint_pos_out_of_limit",
            "joint_pos_out_of_manual_limit",
            "joint_vel_out_of_limit",
            "joint_vel_out_of_manual_limit",
            "root_height_below_minimum",
            "time_out",
        ],
    },
)
