# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Cosmos on compatible Isaac Lab cameras: :func:`cosmos_camera` and :func:`apply_cosmos`."""

from __future__ import annotations

import logging
import math
from dataclasses import fields, is_dataclass
from typing import Any, Literal

from isaaclab.sensors import CameraCfg
from isaaclab.sim import FisheyeCameraCfg
from isaaclab.utils import replace
from isaaclab.utils.modifiers import ModifierCfg

from isaaclab_experimental.image_transfer import center_crop_resize, depth_to_control

from .._protocol import CANVAS_ASPECT_RATIOS, DEFAULT_ENDPOINT, request
from .control_profiles import blur_processor, depth_processor, edge_processor
from .cosmos_model_cfg import CosmosModelCfg
from .cosmos_modifier_cfg import CosmosTransferModifierCfg

logger = logging.getLogger(__name__)

COSMOS_CANVASES = tuple(CANVAS_ASPECT_RATIOS)
"""Image sizes ``(height, width)`` the Cosmos service accepts."""


def cosmos_camera(
    camera: CameraCfg,
    model: CosmosModelCfg,
    *,
    near: float = 0.1,
    far: float = 2.0,
    edge_thresholds: tuple[int, int] = (100, 200),
) -> CameraCfg:
    """Return a copy of ``camera`` whose ``rgb`` output is generated by Cosmos at the camera's size.

    The copy renders the control input at the Cosmos canvas closest to the camera's aspect ratio, widening the lens
    aperture so the camera's original view is the canvas's center crop. Its chain prepares controls with
    :func:`depth_processor`, :func:`edge_processor`, or :func:`blur_processor` (``model.modality``), generates with
    Cosmos, and scales the result
    back to the camera's width and height. Observation terms that read ``rgb`` keep their image shape; the camera's
    ``image_shape`` and intrinsics describe the canvas.

    Args:
        camera: Pinhole camera publishing only ``rgb``, for example a task's policy camera.
        model: Cosmos service connection, prompt and control type (``"depth"``, ``"edge"``, or ``"blur"``).
        near: Depth rendered white [m], for depth control.
        far: Depth rendered black [m], for depth control.
        edge_thresholds: Lower and upper Canny thresholds, for edge control.

    Returns:
        The Cosmos camera configuration.

    Raises:
        ValueError: If the camera publishes outputs other than ``rgb``, already has modifiers, uses a fisheye lens,
            or the control type is unsupported.
    """
    if model.modality not in ("depth", "edge", "blur"):
        raise ValueError(f"Cosmos cameras support depth, edge, or blur control, got {model.modality!r}.")
    if list(camera.data_types) != ["rgb"]:
        raise ValueError(
            f"A Cosmos camera publishes only 'rgb'; this camera requests {camera.data_types}. "
            "Use a camera that observes rgb only."
        )
    if camera.modifiers:
        raise ValueError("The camera already has modifiers; Cosmos replaces its rgb output.")
    canvas_height, canvas_width = min(
        COSMOS_CANVASES, key=lambda size: abs(math.log(size[1] / size[0] * camera.height / camera.width))
    )
    if model.modality == "depth":
        input_name, chain = depth_processor(model, near=near, far=far)
    elif model.modality == "edge":
        input_name, chain = edge_processor(model, lower=edge_thresholds[0], upper=edge_thresholds[1])
    else:
        input_name, chain = blur_processor(model)
    if (camera.height, camera.width) != (canvas_height, canvas_width):
        chain.append(ModifierCfg(func=center_crop_resize, params={"width": camera.width, "height": camera.height}))
    return replace(
        camera,
        width=canvas_width,
        height=canvas_height,
        spawn=_canvas_spawn(camera, canvas_height, canvas_width),
        modifiers={input_name: chain},
    )


def service_capabilities(
    endpoint: str = DEFAULT_ENDPOINT, timeout: float = 5.0, *, require_idle: bool = False
) -> dict[str, Any]:
    """Return the running Cosmos service's capabilities, such as its episode cap and independent reset support.

    Args:
        endpoint: Cosmos service endpoint.
        timeout: Connection and response timeout [s].
        require_idle: Reject a busy service before configuring a new camera session.

    Returns:
        The capabilities reported by ``isaaclab cosmos status``.

    Raises:
        RuntimeError: If the service is unavailable, or busy when require_idle is True.
    """
    try:
        reply, _ = request(endpoint, {"op": "status"}, timeout=timeout)
    except OSError as error:
        raise RuntimeError(
            f"Cosmos service at {endpoint} is unavailable or still starting; wait for its ready message, "
            "or start isaaclab-cosmos-server as described in cosmos_service.md."
        ) from error
    if require_idle and reply.get("session_active", False):
        raise RuntimeError(
            f"Cosmos service at {endpoint} already has an active camera session; close the other training/play "
            "process or choose another service with --cosmos_endpoint."
        )
    return reply["capabilities"]


def service_max_episode_frames(endpoint: str = DEFAULT_ENDPOINT, timeout: float = 5.0) -> int | None:
    """Return the running Cosmos service's episode cap in frames, or None when it has no cap.

    Args:
        endpoint: Cosmos service endpoint.
        timeout: Connection and response timeout [s].

    Returns:
        The cap set with ``isaaclab-cosmos-server --max-episode-frames``.

    Raises:
        RuntimeError: If the service is not running.
    """
    return service_capabilities(endpoint, timeout)["max_episode_frames"]


def apply_cosmos(
    env_cfg: Any,
    *,
    prompt: str | list[str] | None = None,
    camera: str | None = None,
    control: Literal["depth", "edge", "blur"] | None = None,
    near: float | None = None,
    far: float | None = None,
    endpoint: str | None = None,
    max_episode_frames: int | None | Literal["service"] = "service",
    transport: Literal["auto", "cuda_ipc", "socket"] | None = None,
    num_envs: int | None = None,
) -> None:
    """Put Cosmos on a task's camera in place.

    Selects the scene camera publishing only ``rgb`` (or ``camera``) and replaces it with :func:`cosmos_camera`. It
    sets the environment count, whose cameras the service generates as one batch, and derives the episode budget
    without changing capture timing. For an existing Cosmos camera, it updates settings without rebuilding its
    modifier chain. Tasks must read the camera image
    from its output; Direct tasks that size their observation space from the camera configuration are not
    supported, because the camera renders at the Cosmos canvas.

    Args:
        env_cfg: Task environment configuration.
        prompt: Appearance prompt, or a list: cycled per episode for one environment, one per environment for
            several (see :attr:`CosmosModelCfg.prompt`). None preserves an existing camera's prompt.
        camera: Scene camera name. Defaults to None, which selects the only rgb camera.
        control: Control type: ``"depth"``, ``"edge"``, or ``"blur"``. None preserves a preset or uses depth.
            An existing preset's control type cannot be changed here.
        near: Depth rendered white [m]. None preserves a preset or uses 0.1.
        far: Depth rendered black [m]. None preserves a preset or uses 2.0.
        endpoint: Cosmos service endpoint. None preserves a preset or uses the default endpoint.
        max_episode_frames: The service's episode cap in frames, ``1 + 4*k`` with ``k >= 1``, or None for no cap.
            Defaults to ``"service"``, which asks the running service.
        transport: How images move to and from the service. None preserves a preset or uses auto.
        num_envs: Environments to generate together. Defaults to None, which uses one. The session requests this
            count from the service. Several need compiled inference with per-view caches for independent resets,
            and enough GPU memory for the batch.

    Raises:
        ValueError: If no single rgb camera can be selected, the selected entity is not a suitable camera, sensors
            update eagerly, the camera renders asynchronously, the episode cap is invalid, or the service cannot
            batch ``num_envs`` environments.
        RuntimeError: If capabilities are read from a service that is not running.
    """
    num_envs = 1 if num_envs is None else num_envs
    if type(num_envs) is not int or num_envs < 1:
        raise ValueError(f"Cosmos needs a positive number of environments, got {num_envs!r}.")
    name = camera or _select_camera(env_cfg.scene)
    camera_cfg = getattr(env_cfg.scene, name, None)
    if not isinstance(camera_cfg, CameraCfg):
        raise ValueError(f"Scene entity {name!r} is not a camera.")
    transfers = [
        item for chain in camera_cfg.modifiers.values() for item in chain if isinstance(item, CosmosTransferModifierCfg)
    ]
    if len(transfers) > 1:
        raise ValueError("The selected camera has several Cosmos modifiers; configure their settings explicitly.")
    existing = transfers[0].backend if transfers else None
    if existing is not None and control is not None and control != existing.modality:
        raise ValueError(
            f"This Cosmos preset prepares {existing.modality} controls; omit --cosmos_control or select "
            "an ordinary RGB camera task with --cosmos to use another control."
        )
    control = control or (existing.modality if existing is not None else "depth")
    endpoint = endpoint or (existing.endpoint if existing is not None else DEFAULT_ENDPOINT)
    transport = transport or (existing.transport if existing is not None else "auto")
    prompt = existing.prompt if prompt is None and existing is not None else prompt
    if control != "depth" and (near is not None or far is not None):
        raise ValueError("--cosmos_near and --cosmos_far apply only to depth control.")
    capabilities = (
        service_capabilities(endpoint, require_idle=True) if max_episode_frames == "service" or num_envs > 1 else {}
    )
    cap = capabilities["max_episode_frames"] if max_episode_frames == "service" else max_episode_frames
    if num_envs > 1 and not capabilities.get("partial_resets", False):
        raise ValueError(
            "Several Cosmos environments need a Framework runtime with per-view caches and compiled inference "
            "for independent resets; start isaaclab-cosmos-server without --no-compile."
        )
    if cap is not None and (type(cap) is not int or cap < 5 or (cap - 1) % 4):
        raise ValueError(f"The Cosmos episode cap must be 1 + 4*k frames with k >= 1, or None, got {cap!r}.")
    if prompt is None:
        logger.warning("Cosmos runs without a prompt; pass --cosmos_prompt to describe the scene.")
    if env_cfg.scene.num_envs != num_envs:
        logger.info("Cosmos generates %d environment(s); the task default was %d.", num_envs, env_cfg.scene.num_envs)
        env_cfg.scene.num_envs = num_envs
    if not env_cfg.scene.lazy_sensor_update:
        raise ValueError("Cosmos needs scene.lazy_sensor_update=True so each image matches its simulation state.")
    if getattr(camera_cfg.renderer_cfg, "async_rendering", False):
        raise ValueError("Cosmos needs synchronous rendering; set the camera's renderer_cfg.async_rendering=False.")
    if existing is None and hasattr(env_cfg, "observation_space") and not hasattr(env_cfg, "observations"):
        logger.warning(
            "Direct tasks that size their observation space from the camera configuration do not support --cosmos; "
            "the camera renders at the Cosmos canvas."
        )

    # Count actual captures at the sensor's existing cadence; never slow policy observations to fit a cap.
    step_dt = env_cfg.sim.dt * env_cfg.decimation
    episode_steps = math.ceil(env_cfg.episode_length_s / step_dt - 1e-9)
    # A sensor updates once its elapsed time reaches update_period - 1e-6 (see SensorBase).
    steps_per_capture = max(1, math.ceil((camera_cfg.update_period - 1e-6) / step_dt - 1e-9))
    frames = math.ceil(episode_steps / steps_per_capture) + 1
    budget = 1 + 4 * math.ceil((frames - 1) / 4)
    if cap is not None and budget > cap:
        raise ValueError(
            f"The task needs a Cosmos budget of {budget} frames, but the service cap is {cap}. "
            "Raise --max-episode-frames on the server (0 removes the cap), shorten the episode, or explicitly "
            "increase the camera update_period. Capture timing was not changed."
        )
    model = replace(
        existing or CosmosModelCfg(),
        endpoint=endpoint,
        prompt=prompt,
        modality=control,
        max_episode_frames=budget,
        transport=transport,
    )
    if existing is None:
        camera_cfg = cosmos_camera(
            camera_cfg, model, near=0.1 if near is None else near, far=2.0 if far is None else far
        )
    else:
        modifiers = {}
        for input_name, chain in camera_cfg.modifiers.items():
            updated = []
            for item in chain:
                if isinstance(item, CosmosTransferModifierCfg):
                    item = replace(item, backend=model)
                elif item.func is depth_to_control and (near is not None or far is not None):
                    params = dict(item.params)
                    params.update({key: value for key, value in (("near", near), ("far", far)) if value is not None})
                    if not (
                        math.isfinite(params["near"])
                        and math.isfinite(params["far"])
                        and 0 <= params["near"] < params["far"]
                    ):
                        raise ValueError("Cosmos depth bounds must be finite and satisfy 0 <= near < far.")
                    item = replace(item, params=params)
                updated.append(item)
            modifiers[input_name] = updated
        camera_cfg = replace(camera_cfg, modifiers=modifiers)
    setattr(env_cfg.scene, name, camera_cfg)
    capture_hz = 1 / (steps_per_capture * step_dt)
    logger.info(
        "Cosmos camera %s: %d environment(s), %d-frame budget, %.3f captures/s, %.3f generated updates/s "
        "after the initial frame (simulation time).",
        name,
        num_envs,
        budget,
        capture_hz,
        capture_hz / 4,
    )
    if isinstance(prompt, (list, tuple)):
        logger.info(
            "Cosmos prompt list: %s.",
            "cycles across episodes" if num_envs == 1 else "assigned per environment and kept across resets",
        )


def _select_camera(scene: Any) -> str:
    """Return the name of the scene's only camera that publishes only rgb."""
    names = []
    if is_dataclass(scene):
        for field in fields(scene):
            value = getattr(scene, field.name)
            if isinstance(value, CameraCfg) and list(value.data_types) == ["rgb"]:
                names.append(field.name)
    if len(names) != 1:
        raise ValueError(f"Choose the Cosmos camera with --cosmos_camera; rgb cameras in this scene: {names}.")
    return names[0]


def _canvas_spawn(camera: CameraCfg, canvas_height: int, canvas_width: int) -> Any:
    """Widen the pinhole aperture so the camera's original view is the canvas's center crop."""
    spawn = camera.spawn
    if isinstance(spawn, FisheyeCameraCfg):
        raise ValueError("Cosmos cameras need a pinhole lens; a fisheye view is not a center crop of a wider view.")
    if spawn is None:
        if canvas_width * camera.height != canvas_height * camera.width:
            logger.warning("The Cosmos canvas changes this camera's aspect ratio; its view is cropped.")
        return spawn
    # Renderers use square pixels, so the vertical aperture follows the horizontal one and the image size.
    vertical = spawn.horizontal_aperture * camera.height / camera.width
    if canvas_width * vertical >= canvas_height * spawn.horizontal_aperture:
        return replace(spawn, horizontal_aperture=vertical * canvas_width / canvas_height, vertical_aperture=vertical)
    return replace(spawn, vertical_aperture=spawn.horizontal_aperture * canvas_height / canvas_width)
