# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""One path for Cosmos on any Isaac Lab camera: :func:`cosmos_camera` and :func:`apply_cosmos`."""

from __future__ import annotations

import logging
import math
from dataclasses import fields, is_dataclass
from typing import Any, Literal

from isaaclab.sensors import CameraCfg
from isaaclab.sim import FisheyeCameraCfg
from isaaclab.utils import replace
from isaaclab.utils.modifiers import ModifierCfg

from isaaclab_experimental.image_transfer import center_crop_resize

from .._protocol import CANVAS_ASPECT_RATIOS, request
from .control_profiles import depth_processor, edge_processor
from .cosmos_model_cfg import CosmosModelCfg

logger = logging.getLogger(__name__)

COSMOS_CANVASES = tuple(CANVAS_ASPECT_RATIOS)
"""Image sizes ``(height, width)`` the Cosmos service accepts."""


def cosmos_camera(
    camera: CameraCfg,
    model: CosmosModelCfg,
    *,
    near: float = 0.1,
    far: float = 2.0,
    edge_thresholds: tuple[int, int] = (100, 200),
) -> CameraCfg:
    """Return a copy of ``camera`` whose ``rgb`` output is generated by Cosmos at the camera's size.

    The copy renders the control input at the Cosmos canvas closest to the camera's aspect ratio, widening the lens
    aperture so the camera's original view is the canvas's center crop. Its chain prepares controls with
    :func:`depth_processor` or :func:`edge_processor` (``model.modality``), generates with Cosmos, scales the result
    back to the camera's width and height. Observation terms that read ``rgb`` keep their image shape; the camera's
    ``image_shape`` and intrinsics describe the canvas.

    Args:
        camera: Pinhole camera publishing only ``rgb``, for example a task's policy camera.
        model: Cosmos service connection, prompt and control type (``"depth"`` or ``"edge"``).
        near: Depth rendered white [m], for depth control.
        far: Depth rendered black [m], for depth control.
        edge_thresholds: Lower and upper Canny thresholds, for edge control.

    Returns:
        The Cosmos camera configuration.

    Raises:
        ValueError: If the camera publishes outputs other than ``rgb``, already has modifiers, uses a fisheye lens,
            or the control type is unsupported.
    """
    if model.modality not in ("depth", "edge"):
        raise ValueError(f"Cosmos cameras support depth or edge control, got {model.modality!r}.")
    if list(camera.data_types) != ["rgb"]:
        raise ValueError(
            f"A Cosmos camera publishes only 'rgb'; this camera requests {camera.data_types}. "
            "Use a camera that observes rgb only."
        )
    if camera.modifiers:
        raise ValueError("The camera already has modifiers; Cosmos replaces its rgb output.")
    canvas_height, canvas_width = min(
        COSMOS_CANVASES, key=lambda size: abs(math.log(size[1] / size[0] * camera.height / camera.width))
    )
    if model.modality == "depth":
        input_name, chain = depth_processor(model, near=near, far=far)
    else:
        input_name, chain = edge_processor(model, lower=edge_thresholds[0], upper=edge_thresholds[1])
    if (camera.height, camera.width) != (canvas_height, canvas_width):
        chain.append(ModifierCfg(func=center_crop_resize, params={"width": camera.width, "height": camera.height}))
    return replace(
        camera,
        width=canvas_width,
        height=canvas_height,
        spawn=_canvas_spawn(camera, canvas_height, canvas_width),
        modifiers={input_name: chain},
    )


def service_max_episode_frames(endpoint: str = "tcp://127.0.0.1:5555", timeout: float = 5.0) -> int | None:
    """Return the running Cosmos service's episode cap in frames, or None when it has no cap.

    Args:
        endpoint: Cosmos service endpoint.
        timeout: Connection and response timeout [s].

    Returns:
        The cap set with ``isaaclab-cosmos-server --max-episode-frames``.

    Raises:
        RuntimeError: If the service is not running.
    """
    try:
        reply, _ = request(endpoint, {"op": "status"}, timeout=timeout)
    except OSError as error:
        raise RuntimeError(
            f"No Cosmos service at {endpoint}; start isaaclab-cosmos-server as described in cosmos_service.md."
        ) from error
    return reply["capabilities"]["max_episode_frames"]


def apply_cosmos(
    env_cfg: Any,
    *,
    prompt: str | list[str] | None,
    camera: str | None = None,
    control: Literal["depth", "edge"] = "depth",
    near: float = 0.1,
    far: float = 2.0,
    endpoint: str = "tcp://127.0.0.1:5555",
    max_episode_frames: int | None | Literal["service"] = "service",
) -> None:
    """Put Cosmos on a task's camera in place.

    Selects the scene camera publishing only ``rgb`` (or ``camera``) and replaces it with :func:`cosmos_camera`. It
    uses one environment and, when an episode would exceed the service's episode cap, makes the camera capture every
    few environment steps. Tasks must read the camera image from its output; Direct tasks that size their observation
    space from the camera configuration are not supported, because the camera renders at the Cosmos canvas.

    Args:
        env_cfg: Task environment configuration.
        prompt: Appearance prompt, or a list cycled per episode.
        camera: Scene camera name. Defaults to None, which selects the only rgb camera.
        control: Control type: ``"depth"`` or ``"edge"``.
        near: Depth rendered white [m], for depth control.
        far: Depth rendered black [m], for depth control.
        endpoint: Cosmos service endpoint.
        max_episode_frames: The service's episode cap in frames, ``1 + 4*k``, or None for no cap. Defaults to
            ``"service"``, which asks the running service.

    Raises:
        ValueError: If no single rgb camera can be selected, the selected entity is not a suitable camera, sensors
            update eagerly, the camera renders asynchronously, or the episode cap is invalid.
        RuntimeError: If the cap is read from a service that is not running.
    """
    cap = service_max_episode_frames(endpoint) if max_episode_frames == "service" else max_episode_frames
    if cap is not None and (type(cap) is not int or cap < 1 or (cap - 1) % 4):
        raise ValueError(f"The Cosmos episode cap must be 1 + 4*k frames or None, got {cap!r}.")
    if prompt is None:
        logger.warning("Cosmos runs without a prompt; pass --cosmos_prompt to describe the scene.")
    name = camera or _select_camera(env_cfg.scene)
    camera_cfg = getattr(env_cfg.scene, name, None)
    if not isinstance(camera_cfg, CameraCfg):
        raise ValueError(f"Scene entity {name!r} is not a camera.")
    if env_cfg.scene.num_envs != 1:
        logger.warning("Cosmos serves one camera view; using 1 environment instead of %d.", env_cfg.scene.num_envs)
        env_cfg.scene.num_envs = 1
    if not env_cfg.scene.lazy_sensor_update:
        raise ValueError("Cosmos needs scene.lazy_sensor_update=True so each image matches its simulation state.")
    if getattr(camera_cfg.renderer_cfg, "async_rendering", False):
        raise ValueError("Cosmos needs synchronous rendering; set the camera's renderer_cfg.async_rendering=False.")
    if hasattr(env_cfg, "observation_space") and not hasattr(env_cfg, "observations"):
        logger.warning(
            "Direct tasks that size their observation space from the camera configuration do not support --cosmos; "
            "the camera renders at the Cosmos canvas."
        )

    # Count in whole environment steps so rounding cannot push an episode past the cap.
    step_dt = env_cfg.sim.dt * env_cfg.decimation
    episode_steps = math.ceil(env_cfg.episode_length_s / step_dt - 1e-9)
    steps_per_capture = max(1, math.ceil(camera_cfg.update_period / step_dt - 1e-9))
    frames = math.ceil(episode_steps / steps_per_capture) + 1
    if cap is not None and frames > cap:
        steps_per_capture = math.ceil(episode_steps / (cap - 1))
        frames = math.ceil(episode_steps / steps_per_capture) + 1
        logger.warning(
            "Cosmos camera captures every %d environment steps so an episode fits the %d-frame cap; raise the cap "
            "with 'isaaclab-cosmos-server --max-episode-frames' to keep the camera's rate.",
            steps_per_capture,
            cap,
        )
        camera_cfg = replace(camera_cfg, update_period=steps_per_capture * step_dt)
    budget = 1 + 4 * math.ceil((frames - 1) / 4)
    if cap is not None and budget > cap:
        raise AssertionError(f"Cosmos episode budget {budget} exceeds the cap {cap}.")
    model = CosmosModelCfg(endpoint=endpoint, prompt=prompt, modality=control, max_episode_frames=budget)
    setattr(env_cfg.scene, name, cosmos_camera(camera_cfg, model, near=near, far=far))


def _select_camera(scene: Any) -> str:
    """Return the name of the scene's only camera that publishes only rgb."""
    names = []
    if is_dataclass(scene):
        for field in fields(scene):
            value = getattr(scene, field.name)
            if isinstance(value, CameraCfg) and list(value.data_types) == ["rgb"]:
                names.append(field.name)
    if len(names) != 1:
        raise ValueError(f"Choose the Cosmos camera with --cosmos_camera; rgb cameras in this scene: {names}.")
    return names[0]


def _canvas_spawn(camera: CameraCfg, canvas_height: int, canvas_width: int) -> Any:
    """Widen the pinhole aperture so the camera's original view is the canvas's center crop."""
    spawn = camera.spawn
    if isinstance(spawn, FisheyeCameraCfg):
        raise ValueError("Cosmos cameras need a pinhole lens; a fisheye view is not a center crop of a wider view.")
    if spawn is None:
        if canvas_width * camera.height != canvas_height * camera.width:
            logger.warning("The Cosmos canvas changes this camera's aspect ratio; its view is cropped.")
        return spawn
    # Renderers use square pixels, so the vertical aperture follows the horizontal one and the image size.
    vertical = spawn.horizontal_aperture * camera.height / camera.width
    if canvas_width * vertical >= canvas_height * spawn.horizontal_aperture:
        return replace(spawn, horizontal_aperture=vertical * canvas_width / canvas_height, vertical_aperture=vertical)
    return replace(spawn, vertical_aperture=spawn.horizontal_aperture * canvas_height / canvas_width)
