# Copyright 2026 Enactic, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

robot:
  root_frame: world
  components:
    - primary_arm
    - primary_arm_end_effector

body:
  type: robot
  enabled: false
  product: openarm_v2.0
  config: body
  inertials: nominal
  link_name: openarm_body_link0
  connection:
    parent: world
    origin:
      x: 0.0
      y: 0.0
      z: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
  reflect:
    x: 1
    y: 1
    z: 1
  limit_override_joints: {}

primary_arm:
  type: robot
  enabled: true
  product: openarm_v2.0
  config: arm
  inertials: nominal
  prefix: openarm_left_
  connection:
    parent: world
    origin:
      x: 0.0
      y: 0.0
      z: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
  reflect:
    x: 1
    y: -1
    z: 1
    include:
      links: [base_link, link1, link2, link5, link6, link7]
      joints: [joint1, joint2, joint3, joint5, joint6, joint7]
      reference_points: [ee_mount_point]
  limit_override_joints: {}

secondary_arm:
  type: robot
  enabled: false
  product: openarm_v2.0
  config: arm
  inertials: nominal
  prefix: openarm_right_
  connection:
    parent: world
    origin:
      x: 0.0
      y: 0.0
      z: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
  reflect:
    x: 1
    y: 1
    z: 1
  limit_override_joints: {}

primary_arm_end_effector:
  type: end_effector
  enabled: true
  product: pinch_gripper
  config: null
  inertials: nominal
  prefix: openarm_left_
  connection:
    attach_to: primary_arm
    parent_reference_point: ee_mount_point
    parent: null
    origin: null
  reflect:
    x: 1
    y: -1
    z: 1
  limit_override_joints: {}

secondary_arm_end_effector:
  type: end_effector
  enabled: false
  product: pinch_gripper
  config: null
  inertials: nominal
  prefix: openarm_right_
  connection:
    attach_to: secondary_arm
    parent_reference_point: ee_mount_point
    parent: null
    origin: null
  reflect:
    x: 1
    y: 1
    z: 1
  limit_override_joints: {}
