# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - right_arm_joint1
    - right_arm_joint2
    - right_arm_joint3
    - right_arm_joint4
    - right_arm_joint5
    - right_arm_joint6
    - right_arm_joint7


default_q: [0.1535, 1.0087, 0.0895, 1.5743, -0.2422, -0.0009, -0.9143]

acceleration_limits: [
   10,10,10,10,10,10,10
]

jerk_limits: [
   10000,10000,10000,10000,10000,10000,10000
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:
    - {name: leg_joint1, rule: fixed, value: 0.8}
    - {name: leg_joint2, rule: fixed, value: 2.3}
    - {name: leg_joint3, rule: fixed, value: 1.55}
    - {name: leg_joint4, rule: fixed, value: 0.0}
    - {name: head_joint1, rule: fixed, value: 0.0}
    - {name: left_arm_joint1, rule: fixed, value: -0.5480}
    - {name: head_joint2, rule: fixed, value: 0.36}
    - {name: left_arm_joint2, rule: fixed, value: -0.6551}
    - {name: left_arm_joint3, rule: fixed, value: 2.407}
    - {name: left_arm_joint4, rule: fixed, value: 1.3641}
    - {name: left_arm_joint5, rule: fixed, value: -0.4416}
    - {name: left_arm_joint6, rule: fixed, value: 0.1168}
    - {name: left_arm_joint7, rule: fixed, value: 1.2308}
    - {name: left_gripper_left_joint, rule: fixed, value: 0.0}
    - {name: left_gripper_right_joint, rule: fixed, value: 0.0}
    - {name: right_suction_cup_joint1, rule: fixed, value: 0.0}


# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  - right_arm_link1:
    - "center": [-0.0, -0.0, -0.009]
      "radius": 0.07
    - "center": [-0.0, -0.0, -0.06]
      "radius": 0.05
  - right_arm_link2:
    - "center": [-0.0, -0.149, -0.0]
      "radius": 0.06
    - "center": [-0.0, -0.083, -0.0]
      "radius": 0.06
    - "center": [-0.0, -0.02, -0.0]
      "radius": 0.08
  - right_arm_link3:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.06
    - "center": [0.0, -0.0, -0.138]
      "radius": 0.05
    - "center": [0.0, -0.0, -0.049]
      "radius": 0.05646
    - "center": [0.0, -0.0, -0.095]
      "radius": 0.05313
  - right_arm_link4:
    - "center": [0.0, -0.078, -0.0]
      "radius": 0.06
    - "center": [0.0, -0.017, -0.0]
      "radius": 0.07
  - right_arm_link5:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.06
    - "center": [-0.0, 0.0, -0.192]
      "radius": 0.06
    - "center": [-0.0, 0.0, -0.067]
      "radius": 0.06649
    - "center": [-0.0, 0.0, -0.131]
      "radius": 0.06316
  - right_arm_link6:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.06
  - right_arm_link7:
    - "center": [-0.054, -0.0, 0.0]
      "radius": 0.05
    - "center": [-0.058, 0.052, -0.002]
      "radius": 0.06
    - "center": [-0.007, 0.0, -0.064]
      "radius": 0.035
  - right_suction_cup_base_link:
    - "center": [-0.028, -0.0, 0.0]
      "radius": 0.05
    - "center": [-0.08, -0.0, 0.0]
      "radius": 0.02
    - "center": [-0.137, -0.0, 0.0]
      "radius": 0.02
    - "center": [-0.099, -0.0, 0.0]
      "radius": 0.02
    - "center": [-0.118, -0.0, 0.0]
      "radius": 0.02
  - right_suction_cup_link1:
    - "center": [0.0, -0.017, 0.0]
      "radius": 0.02
    - "center": [0.0, -0.035, 0.0]
      "radius": 0.02
    - "center": [0.0, -0.057, 0.0]
      "radius": 0.02
    - "center": [0.0, -0.073, 0.0]
      "radius": 0.025
