# Copyright 2026 Enactic, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

links:
  - base_link
  - link1
  - link2
  - link3
  - link4
  - link5
  - link6
  - link7
joints:
  joint1:
    type: revolute
    parent: base_link
    child: link1
  joint2:
    type: revolute
    parent: link1
    child: link2
  joint3:
    type: revolute
    parent: link2
    child: link3
  joint4:
    type: revolute
    parent: link3
    child: link4
  joint5:
    type: revolute
    parent: link4
    child: link5
  joint6:
    type: revolute
    parent: link5
    child: link6
  joint7:
    type: revolute
    parent: link6
    child: link7
