[pytest]
testpaths = tests
python_files = *.py
markers =
    bugs: tests for known bugs
    gpu: tests that require a GPU
    docker: tests that only run inside Docker
    slow: tests that take long time to run
timeout = 1200
