# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

__all__ = [
    "MESH_APPROXIMATION_TOKENS",
    "PHYSX_MESH_COLLISION_CFGS",
    "USD_MESH_COLLISION_CFGS",
    "activate_contact_sensors",
    "apply_collision_properties",
    "apply_fixed_tendon_properties",
    "apply_mass_properties",
    "apply_drive",
    "apply_joint_drive_properties",
    "apply_mesh_collision",
    "apply_mesh_collision_properties",
    "apply_namespaced",
    "apply_rigid_body_properties",
    "apply_spatial_tendon_properties",
    "define_actuator_properties",
    "define_articulation_root_properties",
    "define_collision_properties",
    "define_deformable_body_properties",
    "define_mass_properties",
    "define_mesh_collision_properties",
    "define_rigid_body_properties",
    "modify_articulation_root_properties",
    "modify_collision_properties",
    "modify_deformable_body_properties",
    "modify_fixed_tendon_properties",
    "modify_joint_drive_properties",
    "modify_mass_properties",
    "modify_mesh_collision_properties",
    "modify_rigid_body_properties",
    "modify_spatial_tendon_properties",
    "ArticulationRootBaseCfg",
    "BoundingCubePropertiesCfg",
    "BoundingSpherePropertiesCfg",
    "CollisionBaseCfg",
    "CollisionFragment",
    "DeformableBodyPropertiesBaseCfg",
    "DeformableBodyPropertiesCfg",
    "FixedTendonFragment",
    "JointDriveBaseCfg",
    "MassCfg",
    "MassFragment",
    "JointDriveFragment",
    "MassPropertiesCfg",
    "MeshCollisionBaseCfg",
    "MeshCollisionFragment",
    "RigidBodyFragment",
    "SchemaFragment",
    "SpatialTendonFragment",
    "UsdPhysicsCollisionCfg",
    "UsdPhysicsDriveCfg",
    "UsdPhysicsMeshCollisionCfg",
    "UsdPhysicsRigidBodyCfg",
    "MujocoJointDrivePropertiesCfg",
    "MujocoRigidBodyPropertiesCfg",
    "NewtonArticulationRootPropertiesCfg",
    "NewtonCollisionPropertiesCfg",
    "NewtonJointDrivePropertiesCfg",
    "NewtonMaterialPropertiesCfg",
    "NewtonMeshCollisionPropertiesCfg",
    "NewtonRigidBodyPropertiesCfg",
    "NewtonSDFCollisionPropertiesCfg",
    "RigidBodyBaseCfg",
]

from .schemas import (
    MESH_APPROXIMATION_TOKENS,
    PHYSX_MESH_COLLISION_CFGS,
    USD_MESH_COLLISION_CFGS,
    activate_contact_sensors,
    apply_collision_properties,
    apply_fixed_tendon_properties,
    apply_mass_properties,
    apply_drive,
    apply_joint_drive_properties,
    apply_mesh_collision,
    apply_mesh_collision_properties,
    apply_namespaced,
    apply_rigid_body_properties,
    apply_spatial_tendon_properties,
    define_articulation_root_properties,
    define_collision_properties,
    define_deformable_body_properties,
    define_mass_properties,
    define_mesh_collision_properties,
    define_rigid_body_properties,
    modify_articulation_root_properties,
    modify_collision_properties,
    modify_deformable_body_properties,
    modify_fixed_tendon_properties,
    modify_joint_drive_properties,
    modify_mass_properties,
    modify_mesh_collision_properties,
    modify_rigid_body_properties,
    modify_spatial_tendon_properties,
)
from .schemas_actuators import (
    define_actuator_properties,
)
from .schemas_cfg import (
    ArticulationRootBaseCfg,
    BoundingCubePropertiesCfg,
    BoundingSpherePropertiesCfg,
    CollisionBaseCfg,
    CollisionFragment,
    DeformableBodyPropertiesBaseCfg,
    DeformableBodyPropertiesCfg,
    FixedTendonFragment,
    JointDriveBaseCfg,
    MassCfg,
    MassFragment,
    JointDriveFragment,
    MassPropertiesCfg,
    MeshCollisionBaseCfg,
    MeshCollisionFragment,
    RigidBodyBaseCfg,
    RigidBodyFragment,
    SchemaFragment,
    SpatialTendonFragment,
    UsdPhysicsCollisionCfg,
    UsdPhysicsDriveCfg,
    UsdPhysicsMeshCollisionCfg,
    UsdPhysicsRigidBodyCfg,
)

# Forwarded to isaaclab_newton.sim.schemas via __getattr__ shim
MujocoJointDrivePropertiesCfg = ...
MujocoRigidBodyPropertiesCfg = ...
NewtonArticulationRootPropertiesCfg = ...
NewtonCollisionPropertiesCfg = ...
NewtonJointDrivePropertiesCfg = ...
NewtonMaterialPropertiesCfg = ...
NewtonMeshCollisionPropertiesCfg = ...
NewtonRigidBodyPropertiesCfg = ...
NewtonSDFCollisionPropertiesCfg = ...
