# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

__all__ = [
    "MESH_APPROXIMATION_TOKENS",
    "PHYSX_MESH_COLLISION_CFGS",
    "USD_MESH_COLLISION_CFGS",
    "activate_contact_sensors",
    "define_articulation_root_properties",
    "define_collision_properties",
    "define_deformable_body_properties",
    "define_mass_properties",
    "define_mesh_collision_properties",
    "define_rigid_body_properties",
    "modify_articulation_root_properties",
    "modify_collision_properties",
    "modify_deformable_body_properties",
    "modify_fixed_tendon_properties",
    "modify_joint_drive_properties",
    "modify_mass_properties",
    "modify_mesh_collision_properties",
    "modify_rigid_body_properties",
    "modify_spatial_tendon_properties",
    "ArticulationRootPropertiesCfg",
    "BoundingCubePropertiesCfg",
    "BoundingSpherePropertiesCfg",
    "CollisionPropertiesCfg",
    "ConvexDecompositionPropertiesCfg",
    "ConvexHullPropertiesCfg",
    "DeformableBodyPropertiesCfg",
    "FixedTendonPropertiesCfg",
    "JointDrivePropertiesCfg",
    "MassPropertiesCfg",
    "MeshCollisionPropertiesCfg",
    "RigidBodyPropertiesCfg",
    "SDFMeshPropertiesCfg",
    "SpatialTendonPropertiesCfg",
    "TriangleMeshPropertiesCfg",
    "TriangleMeshSimplificationPropertiesCfg",
]

from .schemas import (
    MESH_APPROXIMATION_TOKENS,
    PHYSX_MESH_COLLISION_CFGS,
    USD_MESH_COLLISION_CFGS,
    activate_contact_sensors,
    define_articulation_root_properties,
    define_collision_properties,
    define_deformable_body_properties,
    define_mass_properties,
    define_mesh_collision_properties,
    define_rigid_body_properties,
    modify_articulation_root_properties,
    modify_collision_properties,
    modify_deformable_body_properties,
    modify_fixed_tendon_properties,
    modify_joint_drive_properties,
    modify_mass_properties,
    modify_mesh_collision_properties,
    modify_rigid_body_properties,
    modify_spatial_tendon_properties,
)
from .schemas_cfg import (
    ArticulationRootPropertiesCfg,
    BoundingCubePropertiesCfg,
    BoundingSpherePropertiesCfg,
    CollisionPropertiesCfg,
    ConvexDecompositionPropertiesCfg,
    ConvexHullPropertiesCfg,
    DeformableBodyPropertiesCfg,
    FixedTendonPropertiesCfg,
    JointDrivePropertiesCfg,
    MassPropertiesCfg,
    MeshCollisionPropertiesCfg,
    RigidBodyPropertiesCfg,
    SDFMeshPropertiesCfg,
    SpatialTendonPropertiesCfg,
    TriangleMeshPropertiesCfg,
    TriangleMeshSimplificationPropertiesCfg,
)
