# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Testmon subprocess coverage helpers.

pytest-testmon 2.x only tracks coverage in the pytest process. Tests that spawn
child Python processes (for example ``./isaaclab.sh -p scripts/.../train.py``)
need:

1. A ``sitecustomize.py`` shim on ``PYTHONPATH`` so child interpreters call
   :func:`coverage.process_startup` at startup. This is written into a
   repository-local temporary directory rather than ``site-packages`` so it
   works even when ``site-packages`` is read-only (for example inside CI
   containers running as a non-root user).
2. ``COVERAGE_PROCESS_START`` pointing at a config with ``parallel = true`` and
   the :mod:`testmon_coverage_context` plugin, so lines are tagged with the
   active test's node id.
3. Child data merged into Testmon's in-memory coverage via
   :meth:`coverage.CoverageData.update` before each batch is read.

Import the pytest hook functions into ``conftest.py``.
"""

from __future__ import annotations

import contextlib
import os
import shutil
import sysconfig
import warnings
from dataclasses import dataclass
from pathlib import Path

import pytest

_TMONTMP_DIR = ".tmontmp"
_COVERAGE_PROCESS_START = "COVERAGE_PROCESS_START"
_COVERAGE_CONTEXT = "COVERAGE_CONTEXT"
_STATE_KEY = pytest.StashKey["SubprocessCoverageState"]()

# ``sitecustomize`` is imported unconditionally by :mod:`site` at interpreter
# startup (unlike ``usercustomize``, which is gated on ``ENABLE_USER_SITE``), so
# a ``sitecustomize.py`` placed first on ``PYTHONPATH`` reliably runs in every
# child interpreter. ``coverage.process_startup`` is a no-op unless
# ``COVERAGE_PROCESS_START`` is set, so the shim is harmless outside collection.
_SHIM_FILENAME = "sitecustomize.py"
_SHIM_CONTENT = (
    "# Auto-generated by testmon_subprocess_coverage to attribute child-process\n"
    "# coverage back to the active test. No-op unless COVERAGE_PROCESS_START is set.\n"
    "try:\n"
    "    import coverage\n"
    "    coverage.process_startup()\n"
    "except Exception:\n"
    "    pass\n"
)


@dataclass(frozen=True)
class SubprocessCoverageState:
    """Session state for subprocess coverage collection."""

    rc_path: Path
    data_prefix: Path
    shim_dir: Path | None
    enabled: bool
    prev_pythonpath: str | None = None


def _python_lib_omit_patterns() -> list[str]:
    return [os.path.join(value, "*") for key, value in sysconfig.get_paths().items() if key.endswith("lib")]


def _is_testmon_collecting(config: pytest.Config) -> bool:
    tm_conf = getattr(config, "testmon_config", None)
    return tm_conf is not None and tm_conf.collect


def _install_subprocess_shim(shim_dir: Path) -> Path | None:
    """Write a ``sitecustomize.py`` ``process_startup`` shim into ``shim_dir``.

    Returns the shim directory (to be prepended to ``PYTHONPATH``) or ``None``
    if :mod:`coverage` is unavailable or the directory cannot be written.
    """
    try:
        import coverage  # noqa: F401
    except ImportError:
        return None

    try:
        shim_dir.mkdir(parents=True, exist_ok=True)
        (shim_dir / _SHIM_FILENAME).write_text(_SHIM_CONTENT, encoding="utf-8")
    except OSError:
        return None
    return shim_dir


def setup_subprocess_coverage(config: pytest.Config) -> SubprocessCoverageState | None:
    """Configure ``COVERAGE_PROCESS_START`` for the pytest session."""
    if not _is_testmon_collecting(config):
        return None

    rootdir = Path(config.rootpath)
    tmontmp = rootdir / _TMONTMP_DIR
    tmontmp.mkdir(exist_ok=True)

    shim_dir = _install_subprocess_shim(tmontmp / f"shim-{os.getpid()}")
    if shim_dir is None:
        warnings.warn(
            "testmon subprocess coverage: could not install a process_startup sitecustomize shim, "
            "so code executed in child Python processes will not be tracked.",
            stacklevel=1,
        )
        state = SubprocessCoverageState(rc_path=Path(), data_prefix=Path(), shim_dir=None, enabled=False)
        config.stash[_STATE_KEY] = state
        return state

    # Prepend the shim directory (so child interpreters import our
    # ``sitecustomize``) and ``tools/`` (so the coveragerc can load
    # :mod:`testmon_coverage_context`).
    tools_dir = rootdir / "tools"
    prev_pythonpath = os.environ.get("PYTHONPATH")
    pythonpath_entries = [str(shim_dir), str(tools_dir)]
    if prev_pythonpath:
        pythonpath_entries.append(prev_pythonpath)
    os.environ["PYTHONPATH"] = os.pathsep.join(pythonpath_entries)

    data_prefix = tmontmp / f"subprocess-{os.getpid()}"
    rc_path = tmontmp / f"subprocess-{os.getpid()}.coveragerc"
    rc_path.write_text(
        "\n".join(
            [
                "[run]",
                f"data_file = {data_prefix}",
                "parallel = true",
                "plugins = testmon_coverage_context",
                "include =",
                f"    {os.path.join(str(rootdir), '*')}",
                "omit =",
                # The Testmon scratch dir (including our sitecustomize shim) lives
                # under ``rootdir`` but must not be tracked as a test dependency;
                # its per-PID path changes every run and would force reselection.
                f"    {os.path.join(str(tmontmp), '*')}",
                *(f"    {pattern}" for pattern in _python_lib_omit_patterns()),
                "",
            ]
        ),
        encoding="utf-8",
    )
    os.environ[_COVERAGE_PROCESS_START] = str(rc_path.resolve())
    state = SubprocessCoverageState(
        rc_path=rc_path,
        data_prefix=data_prefix,
        shim_dir=shim_dir,
        enabled=True,
        prev_pythonpath=prev_pythonpath,
    )
    config.stash[_STATE_KEY] = state
    return state


def _child_data_files(data_prefix: Path) -> list[Path]:
    if not data_prefix.parent.is_dir():
        return []
    return sorted(p for p in data_prefix.parent.glob(f"{data_prefix.name}.*") if p.is_file())


def combine_subprocess_coverage(config: pytest.Config) -> None:
    """Merge child-process coverage into Testmon's in-memory coverage data."""
    state = config.stash.get(_STATE_KEY, None)
    if state is None or not state.enabled:
        return

    child_files = _child_data_files(state.data_prefix)
    if not child_files:
        return

    collect_plugin = config.pluginmanager.get_plugin("TestmonCollect")
    if collect_plugin is None:
        return

    # ``collect_plugin.testmon.cov`` is a private chain that could change on a
    # future testmon release; fall back to ``None`` rather than raising
    # ``AttributeError`` so a rename simply disables merging instead of breaking
    # the whole test session.
    testmon = getattr(collect_plugin, "testmon", None)
    cov = getattr(testmon, "cov", None)
    if cov is None:
        return

    from coverage import CoverageData

    # ``Coverage`` exposes no public "is running" flag, so fall back to assuming
    # it was running (the normal case while testmon collects) if the private
    # attribute is unavailable, avoiding an ``AttributeError`` that would
    # silently disable merging on a future coverage release.
    was_started = getattr(cov, "_started", True)
    if was_started:
        cov.stop()
    # Always restart coverage in ``finally`` so a merge failure cannot leave it
    # stopped, which would silently record no dependencies for the rest of the
    # session.
    try:
        target = cov.get_data()
        for child_file in child_files:
            child = CoverageData(basename=str(child_file))
            try:
                child.read()
            except Exception:
                continue
            try:
                target.update(child)
            except Exception:
                continue
            child_file.unlink(missing_ok=True)

    finally:
        if was_started:
            cov.start()


def teardown_subprocess_coverage(config: pytest.Config) -> None:
    """Remove temporary subprocess coverage configuration."""
    state = config.stash.get(_STATE_KEY, None)
    if state is None:
        return

    os.environ.pop(_COVERAGE_PROCESS_START, None)
    os.environ.pop(_COVERAGE_CONTEXT, None)
    if state.enabled:
        if state.prev_pythonpath is None:
            os.environ.pop("PYTHONPATH", None)
        else:
            os.environ["PYTHONPATH"] = state.prev_pythonpath
    if state.enabled:
        with contextlib.suppress(OSError):
            state.rc_path.unlink(missing_ok=True)
        for leftover in _child_data_files(state.data_prefix):
            with contextlib.suppress(OSError):
                leftover.unlink(missing_ok=True)
    if state.shim_dir is not None and state.shim_dir.is_dir():
        shutil.rmtree(state.shim_dir, ignore_errors=True)
    if _STATE_KEY in config.stash:
        del config.stash[_STATE_KEY]


def pytest_sessionstart(session: pytest.Session) -> None:
    setup_subprocess_coverage(session.config)


def pytest_runtest_setup(item: pytest.Item) -> None:
    if os.environ.get(_COVERAGE_PROCESS_START):
        os.environ[_COVERAGE_CONTEXT] = item.nodeid


def pytest_runtest_teardown(item: pytest.Item) -> None:
    os.environ.pop(_COVERAGE_CONTEXT, None)


@pytest.hookimpl(wrapper=True, tryfirst=True)
def pytest_runtest_makereport(item: pytest.Item, call: pytest.CallInfo[None]):
    if call.when == "teardown":
        combine_subprocess_coverage(item.config)
    report = yield
    if call.when == "teardown" and hasattr(report, "nodes_files_lines"):
        report.nodes_files_lines = {
            nodeid: {filename: lines for filename, lines in files.items() if Path(filename).suffix}
            for nodeid, files in report.nodes_files_lines.items()
        }
    return report


def pytest_sessionfinish(session: pytest.Session, exitstatus: int) -> None:
    teardown_subprocess_coverage(session.config)
