# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Vendored BAM parameter-loader contracts against the upstream XL330 m6 fit."""

from pathlib import Path

import numpy as np
import pytest

from isaaclab.actuators import BAM_XL330_M6_PARAMS_FILE
from isaaclab.actuators.bam_model import BamMotorParams

pytestmark = pytest.mark.unit


@pytest.fixture(scope="module")
def goldens() -> dict[str, np.ndarray]:
    """Reference data generated by ``scripts/tools/generate_bam_goldens.py``."""
    with np.load(Path(__file__).parent / "data" / "bam_xl330_m6_goldens.npz") as data:
        return {key: data[key] for key in data.files}


@pytest.fixture(scope="module")
def params() -> BamMotorParams:
    """Load the public default file, including its ignored upstream metadata."""
    return BamMotorParams.from_json(BAM_XL330_M6_PARAMS_FILE)


def test_vendored_params_match_reference(params: BamMotorParams, goldens: dict[str, np.ndarray]) -> None:
    """The vendored JSON carries the same constants the goldens were generated with."""
    for name in (
        "kt",
        "R",
        "armature",
        "error_gain",
        "max_pwm",
        "max_current",
        "friction_base",
        "friction_viscous",
        "friction_stribeck",
        "dtheta_stribeck",
        "alpha",
        "load_friction_motor",
        "load_friction_external",
        "load_friction_motor_stribeck",
        "load_friction_external_stribeck",
        "load_friction_motor_quad",
        "load_friction_external_quad",
    ):
        assert getattr(params, name) == float(goldens[f"attr_{name}"]), name
    # m6 = Stribeck + directional load friction + quadratic load coupling.
    assert (params.stribeck, params.load_dependent, params.directional, params.quadratic) == (True, True, True, True)
