# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""USD coefficients and optional BAM authoring tool contracts."""

import json
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest
from newton.actuators import parse_actuator_prim

from pxr import Usd

from isaaclab.actuators.newton import DriveBam, register_bam_actuator_component

pytestmark = [pytest.mark.unit, pytest.mark.filterwarnings("error::DeprecationWarning")]


@pytest.fixture(scope="module")
def goldens() -> dict[str, np.ndarray]:
    """Reference data generated by ``scripts/tools/generate_bam_goldens.py``."""
    with np.load(Path(__file__).parent / "data" / "bam_xl330_m6_goldens.npz") as data:
        return {key: data[key] for key in data.files}


def test_vendored_params_match_reference(goldens: dict[str, np.ndarray]) -> None:
    """The USD fixture carries the same constants the goldens were generated with."""
    register_bam_actuator_component()
    stage = Usd.Stage.Open(str(Path(__file__).parent / "data" / "bam_xl330_m6.usda"))
    prim = stage.GetPrimAtPath("/BamActuator")
    stage.DefinePrim("/servo", "PhysicsRevoluteJoint")
    prim.CreateRelationship("newton:targets").SetTargets(["/servo"])
    params = DriveBam.resolve_arguments(dict(parse_actuator_prim(prim).drive_kwargs))
    for name in (
        "kt",
        "R",
        "error_gain",
        "max_pwm",
        "max_current",
        "friction_base",
        "friction_viscous",
        "friction_stribeck",
        "dtheta_stribeck",
        "alpha",
        "load_friction_motor",
        "load_friction_external",
        "load_friction_motor_stribeck",
        "load_friction_external_stribeck",
        "load_friction_motor_quad",
        "load_friction_external_quad",
    ):
        assert params["resistance" if name == "R" else name] == pytest.approx(float(goldens[f"attr_{name}"])), name
    # m6 = Stribeck + directional load friction + quadratic load coupling.
    assert (params["stribeck"], params["load_dependent"], params["quadratic"]) == (1, 1, 1)


def test_json_import_bakes_coefficients_into_usd(tmp_path, goldens):
    """The optional importer produces a portable asset, even after its input JSON is removed."""
    repo = Path(__file__).resolve().parents[4]
    source = tmp_path / "source.usda"
    output = tmp_path / "output.usda"
    fit = tmp_path / "fit.json"
    source.write_text('#usda 1.0\ndef Xform "Robot" {\n def PhysicsRevoluteJoint "servo" {}\n }\n')
    metadata = {"bam_commit", "motor_name", "model_name", "seed", "num_samples", "dt"}
    values = {
        name.removeprefix("attr_"): value.item()
        for name, value in goldens.items()
        if name.startswith("attr_") and name.removeprefix("attr_") not in metadata
    }
    values.update(actuator="xl330", model="m6")
    fit.write_text(json.dumps(values))
    subprocess.run(
        [
            sys.executable,
            str(repo / "scripts/tools/import_bam_parameters.py"),
            "--input",
            str(source),
            "--output",
            str(output),
            "--articulation",
            "/Robot",
            "--joint_names",
            "servo",
            "--params_file",
            str(fit),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    fit.unlink()
    register_bam_actuator_component()
    stage = Usd.Stage.Open(str(output))
    prim = stage.GetPrimAtPath("/Robot/bam_servo_actuator")
    assert not prim.HasAttribute("newton:paramsFile")
    resolved = DriveBam.resolve_arguments(dict(parse_actuator_prim(prim).drive_kwargs))
    for name, value in values.items():
        if name not in ("actuator", "model", "q_offset", "armature"):
            assert resolved[{"R": "resistance", "kp": "kp_fw"}.get(name, name)] == pytest.approx(value)
    assert (resolved["stribeck"], resolved["load_dependent"], resolved["quadratic"]) == (1, 1, 1)


@pytest.mark.parametrize("coefficient", ["kt", "alpha", "load_friction_external_quad"])
def test_incomplete_usd_coefficients_are_rejected(coefficient):
    """Active friction terms must not silently fall back to zero when a fit is incomplete."""
    register_bam_actuator_component()
    stage = Usd.Stage.Open(str(Path(__file__).parent / "data" / "bam_xl330_m6.usda"))
    prim = stage.GetPrimAtPath("/BamActuator")
    stage.DefinePrim("/servo", "PhysicsRevoluteJoint")
    prim.CreateRelationship("newton:targets").SetTargets(["/servo"])
    values = dict(parse_actuator_prim(prim).drive_kwargs)
    values.pop(coefficient)
    with pytest.raises(ValueError, match=f"missing coefficient.*{coefficient}"):
        DriveBam.resolve_arguments(values)
