# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

name: Build & deploy docs

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'feature/isaacsim-6-0'
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-secrets:
    name: Check secrets
    runs-on: ubuntu-latest
    outputs:
      trigger-deploy: ${{ steps.trigger-deploy.outputs.defined }}
    steps:
    - id: trigger-deploy
      env:
        REPO_NAME: ${{ secrets.REPO_NAME }}
      if: "${{ github.repository == env.REPO_NAME && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/release/')) }}"
      run: echo "defined=true" >> "$GITHUB_OUTPUT"

  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    needs: [check-secrets]

    steps:
    - name: Success
      run: 'true'

  deploy-docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    needs: [check-secrets, build-docs]
    if: needs.check-secrets.outputs.trigger-deploy == 'true'

    steps:
    - name: Success
      run: 'true'
